In [ ]:
import torch
print(torch.cuda.is_available())

True

Vit 3-seed ensemble trianing

In [ ]:
import copy
import json
import math
import random
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image
from sklearn.metrics import accuracy_score, classification_report
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from tqdm.auto import tqdm


# =========================================================
# 1. Mount Drive and copy dataset to local disk
# =========================================================
from google.colab import drive
drive.mount("/content/drive")

DRIVE_ROOT = Path("/content/drive/MyDrive/kaggle_cs3780_sp26")
DRIVE_DATA_DIR = DRIVE_ROOT / "lowdim_export" / "reduced_64x32"
LOCAL_ROOT = Path("/content/local_data")
LOCAL_DATA_DIR = LOCAL_ROOT / "reduced_64x32"

if LOCAL_DATA_DIR.exists():
    print(f"Local dataset already exists at {LOCAL_DATA_DIR}")
else:
    LOCAL_ROOT.mkdir(parents=True, exist_ok=True)
    print(f"Copying dataset from {DRIVE_DATA_DIR} to {LOCAL_DATA_DIR} ...")
    shutil.copytree(DRIVE_DATA_DIR, LOCAL_DATA_DIR)
    print("Copy complete.")

print("Local train dir:", LOCAL_DATA_DIR / "train")
print("Local test dir:", LOCAL_DATA_DIR / "test")
print("Local solution:", LOCAL_DATA_DIR / "solution.csv")


# =========================================================
# 2. Config
# =========================================================
BASE_DATA_ROOT = LOCAL_ROOT
TRAIN_SUBDIR = Path("reduced_64x32/train")
TEST_SUBDIR = Path("reduced_64x32/test")
SOLUTION_CSV = LOCAL_DATA_DIR / "solution.csv"

OUTPUT_DIR = DRIVE_ROOT / "vit_b_16_3seed_ensemble_new"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_SUMMARY_JSON = OUTPUT_DIR / "vit_b_16_3seed_ensemble_new_metrics.json"
OUTPUT_ENSEMBLE_CSV = OUTPUT_DIR / "vit_b_16_3seed_ensemble_new_submission.csv"

IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 22
WARMUP_EPOCHS = 2

LR_HEAD = 1e-3
LR_BACKBONE = 2e-5
WEIGHT_DECAY = 1e-4
LABEL_SMOOTHING = 0.1
FREEZE_BACKBONE_EPOCHS = 2

NUM_WORKERS = 2
PATIENCE = 6
USE_AMP = True
USE_TTA = True

MIXUP_ALPHA = 0.2
USE_MIXUP = True
GRAD_CLIP_NORM = 1.0
EMA_DECAY = 0.999

SEEDS = [2026, 2027, 2028]


# =========================================================
# 3. Utilities
# =========================================================
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
PIN_MEMORY = torch.cuda.is_available()

print("Using device:", DEVICE)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))


def save_json(obj, path: Path):
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)


def model_num_params(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters())


# =========================================================
# 4. Dataset
# =========================================================
class TrainFolderDataset(Dataset):
    def __init__(self, root_dir: Path, transform=None):
        self.root_dir = root_dir
        self.transform = transform

        self.classes = sorted([p.name for p in root_dir.iterdir() if p.is_dir()])
        if not self.classes:
            raise FileNotFoundError(f"No class folders found under {root_dir}")

        self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}
        self.idx_to_class = {i: cls_name for cls_name, i in self.class_to_idx.items()}

        self.samples = []
        for cls_name in self.classes:
            class_dir = root_dir / cls_name
            for img_path in sorted(class_dir.rglob("*.png")):
                self.samples.append((img_path, self.class_to_idx[cls_name]))

        if not self.samples:
            raise FileNotFoundError(f"No PNG files found under {root_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, label


class TestWithSolutionDataset(Dataset):
    def __init__(self, test_dir: Path, solution_csv: Path, class_to_idx: dict[str, int], transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.class_to_idx = class_to_idx

        solution_df = pd.read_csv(solution_csv)
        if "file_name" not in solution_df.columns or "label" not in solution_df.columns:
            raise ValueError("solution.csv must contain columns: file_name, label")

        solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))

        self.samples = []
        image_paths = sorted(test_dir.rglob("*.png"))
        if not image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

        for img_path in image_paths:
            fname = img_path.name
            if fname not in solution_map:
                raise KeyError(f"{fname} not found in solution.csv")
            label_name = solution_map[fname]
            if label_name not in class_to_idx:
                raise KeyError(f"Label {label_name} from solution.csv not found in training classes")
            label_idx = class_to_idx[label_name]
            self.samples.append((img_path, label_idx))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, label, img_path.name


class TestUnlabeledDataset(Dataset):
    def __init__(self, test_dir: Path, transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.image_paths = sorted(test_dir.rglob("*.png"))
        if not self.image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, img_path.name


# =========================================================
# 5. Transforms
# =========================================================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomApply(
        [transforms.RandomAffine(degrees=0, translate=(0.05, 0.05))],
        p=0.5,
    ),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])


# =========================================================
# 6. Load data
# =========================================================
train_dir = BASE_DATA_ROOT / TRAIN_SUBDIR
test_dir = BASE_DATA_ROOT / TEST_SUBDIR

base_train_dataset = TrainFolderDataset(train_dir, transform=train_transform)
test_eval_dataset = TestWithSolutionDataset(
    test_dir=test_dir,
    solution_csv=SOLUTION_CSV,
    class_to_idx=base_train_dataset.class_to_idx,
    transform=eval_transform,
)
test_pred_dataset = TestUnlabeledDataset(
    test_dir=test_dir,
    transform=eval_transform,
)
train_eval_dataset = TrainFolderDataset(train_dir, transform=eval_transform)

persistent = NUM_WORKERS > 0

test_eval_loader = DataLoader(
    test_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

test_pred_loader = DataLoader(
    test_pred_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

train_eval_loader = DataLoader(
    train_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

num_classes = len(base_train_dataset.classes)
idx_to_class = base_train_dataset.idx_to_class

print("num_classes =", num_classes)
print("num_train =", len(base_train_dataset))
print("num_test =", len(test_eval_dataset))


# =========================================================
# 7. Model / EMA
# =========================================================
def build_model(num_classes: int):
    weights = models.ViT_B_16_Weights.DEFAULT
    model = models.vit_b_16(weights=weights)
    in_features = model.heads.head.in_features
    model.heads.head = nn.Linear(in_features, num_classes)
    return model


def freeze_backbone_except_head(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False
    for p in model.heads.head.parameters():
        p.requires_grad = True


def unfreeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = True


class ModelEMA:
    def __init__(self, model, decay=0.999):
        self.decay = decay
        self.ema = copy.deepcopy(model).eval()
        for p in self.ema.parameters():
            p.requires_grad = False

    @torch.no_grad()
    def update(self, model):
        msd = model.state_dict()
        for k, v in self.ema.state_dict().items():
            if v.dtype.is_floating_point:
                v.copy_(v * self.decay + msd[k].detach() * (1.0 - self.decay))
            else:
                v.copy_(msd[k])


# =========================================================
# 8. Scheduler / Mixup
# =========================================================
def cosine_lr_lambda(current_epoch, total_epochs, warmup_epochs):
    if current_epoch < warmup_epochs:
        return float(current_epoch + 1) / float(max(1, warmup_epochs))
    progress = (current_epoch - warmup_epochs) / float(max(1, total_epochs - warmup_epochs))
    return 0.5 * (1.0 + math.cos(math.pi * progress))


def make_optimizer(model, lr):
    return torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=WEIGHT_DECAY)


def mixup_batch(images, labels, alpha=0.2):
    if alpha <= 0:
        return images, labels, labels, 1.0

    lam = np.random.beta(alpha, alpha)
    batch_size = images.size(0)
    index = torch.randperm(batch_size, device=images.device)

    mixed_images = lam * images + (1 - lam) * images[index]
    labels_a = labels
    labels_b = labels[index]
    return mixed_images, labels_a, labels_b, lam


def mixup_loss(criterion, logits, labels_a, labels_b, lam):
    return lam * criterion(logits, labels_a) + (1 - lam) * criterion(logits, labels_b)


# =========================================================
# 9. Train / Eval / Predict
# =========================================================
@torch.no_grad()
def run_eval_epoch(eval_model, loader, criterion, device, use_amp=True):
    eval_model.eval()
    total_loss = 0.0
    all_preds = []
    all_labels = []
    all_file_names = []

    use_amp = use_amp and device.type == "cuda"

    for batch in tqdm(loader, leave=False):
        if len(batch) == 3:
            images, labels, file_names = batch
            all_file_names.extend(file_names)
        else:
            images, labels = batch

        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            logits = eval_model(images)
            loss = criterion(logits, labels)

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc, np.array(all_labels), np.array(all_preds), all_file_names


def run_train_epoch(model, ema_model, loader, criterion, optimizer, scaler, device, use_amp=True):
    model.train()
    total_loss = 0.0
    all_preds = []
    all_labels = []

    use_amp = use_amp and device.type == "cuda"

    for images, labels in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        if USE_MIXUP:
            images, labels_a, labels_b, lam = mixup_batch(images, labels, MIXUP_ALPHA)

        optimizer.zero_grad(set_to_none=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            logits = model(images)
            if USE_MIXUP:
                loss = mixup_loss(criterion, logits, labels_a, labels_b, lam)
            else:
                loss = criterion(logits, labels)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
        scaler.step(optimizer)
        scaler.update()

        ema_model.update(model)

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc


@torch.no_grad()
def predict_logits(eval_model, loader, device, use_amp=True, use_tta=False):
    eval_model.eval()
    all_logits = []
    all_file_names = []
    use_amp = use_amp and device.type == "cuda"

    for images, file_names in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)

        if use_tta:
            variants = [
                images,
                torch.roll(images, shifts=1, dims=2),
                torch.roll(images, shifts=-1, dims=2),
                torch.roll(images, shifts=1, dims=3),
                torch.roll(images, shifts=-1, dims=3),
            ]
            logits_sum = 0
            for v in variants:
                with torch.autocast(device_type="cuda", enabled=use_amp):
                    logits_sum = logits_sum + eval_model(v)
            logits = logits_sum / len(variants)
        else:
            with torch.autocast(device_type="cuda", enabled=use_amp):
                logits = eval_model(images)

        all_logits.append(logits.float().cpu())
        all_file_names.extend(list(file_names))

    all_logits = torch.cat(all_logits, dim=0).numpy()
    return all_logits, all_file_names


def logits_to_pred_df(logits: np.ndarray, file_names: list[str], idx_to_class: dict[int, str]):
    preds = logits.argmax(axis=1)
    if len(preds) != len(file_names):
        raise ValueError(f"Length mismatch: {len(preds)=}, {len(file_names)=}")
    return pd.DataFrame({
        "file_name": file_names,
        "label": [idx_to_class[int(i)] for i in preds],
    })


# =========================================================
# 10. One seed training
# =========================================================
def train_one_seed(seed: int):
    print("\n" + "=" * 80)
    print(f"Starting seed {seed}")
    set_seed(seed)

    seed_output_dir = OUTPUT_DIR / f"seed_{seed}"
    seed_output_dir.mkdir(parents=True, exist_ok=True)

    # train loader must be rebuilt after set_seed for shuffle determinism
    train_dataset = TrainFolderDataset(train_dir, transform=train_transform)
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=persistent,
    )

    model = build_model(num_classes).to(DEVICE)
    ema_model = ModelEMA(model, decay=EMA_DECAY)

    criterion = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)

    freeze_backbone_except_head(model)
    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=LR_HEAD,
        weight_decay=WEIGHT_DECAY,
    )
    scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and DEVICE.type == "cuda"))
    scheduler = torch.optim.lr_scheduler.LambdaLR(
        optimizer,
        lr_lambda=lambda epoch: cosine_lr_lambda(epoch, EPOCHS, WARMUP_EPOCHS)
    )

    history = []
    best_test_acc = -1.0
    best_epoch = -1
    best_state_dict = None
    best_ema_state_dict = None
    best_y_true = None
    best_y_pred = None
    epochs_without_improve = 0

    for epoch in range(1, EPOCHS + 1):
        if epoch == FREEZE_BACKBONE_EPOCHS + 1 and FREEZE_BACKBONE_EPOCHS > 0:
            print(f"[seed {seed}] Unfreezing full backbone at epoch {epoch}")
            unfreeze_all(model)
            optimizer = make_optimizer(model, LR_BACKBONE)
            scheduler = torch.optim.lr_scheduler.LambdaLR(
                optimizer,
                lr_lambda=lambda ep: cosine_lr_lambda(ep, max(EPOCHS - epoch + 1, 1), 1)
            )

        print(f"\n[seed {seed}] Epoch {epoch}/{EPOCHS}")

        train_loss, train_acc = run_train_epoch(
            model, ema_model, train_loader, criterion, optimizer, scaler, DEVICE, USE_AMP
        )

        test_loss, test_acc, y_true, y_pred, _ = run_eval_epoch(
            ema_model.ema, test_eval_loader, criterion, DEVICE, USE_AMP
        )

        print(f"[seed {seed}] train_loss={train_loss:.4f}, train_acc={train_acc:.4f}")
        print(f"[seed {seed}] test_loss={test_loss:.4f}, test_acc={test_acc:.4f}, lr={optimizer.param_groups[0]['lr']:.6g}")

        history.append({
            "epoch": epoch,
            "train_loss": float(train_loss),
            "train_accuracy": float(train_acc),
            "test_loss": float(test_loss),
            "test_accuracy": float(test_acc),
            "lr": float(optimizer.param_groups[0]["lr"]),
        })

        if test_acc > best_test_acc:
            best_test_acc = test_acc
            best_epoch = epoch
            best_state_dict = copy.deepcopy(model.state_dict())
            best_ema_state_dict = copy.deepcopy(ema_model.ema.state_dict())
            best_y_true = y_true.copy()
            best_y_pred = y_pred.copy()
            epochs_without_improve = 0

            best_logits, best_file_names = predict_logits(
                ema_model.ema,
                test_pred_loader,
                DEVICE,
                use_amp=USE_AMP,
                use_tta=USE_TTA,
            )
            best_pred_df = logits_to_pred_df(best_logits, best_file_names, idx_to_class)
            best_pred_df.to_csv(seed_output_dir / "best_test_predictions.csv", index=False)
            np.save(seed_output_dir / "best_test_logits.npy", best_logits)
            print(f"[seed {seed}] Saved new best logits/CSV at epoch {epoch}")
        else:
            epochs_without_improve += 1

        scheduler.step()

        if epochs_without_improve >= PATIENCE:
            print(f"[seed {seed}] Early stopping after {PATIENCE} epochs without improvement.")
            break

    ema_model.ema.load_state_dict(best_ema_state_dict)

    final_train_loss, final_train_acc, _, _, _ = run_eval_epoch(
        ema_model.ema, train_eval_loader, criterion, DEVICE, USE_AMP
    )

    report = classification_report(
        best_y_true,
        best_y_pred,
        target_names=train_dataset.classes,
        output_dict=True,
        zero_division=0,
    )

    metrics = {
        "seed": seed,
        "config": {
            "img_size": IMG_SIZE,
            "batch_size": BATCH_SIZE,
            "epochs": EPOCHS,
            "warmup_epochs": WARMUP_EPOCHS,
            "lr_head": LR_HEAD,
            "lr_backbone": LR_BACKBONE,
            "weight_decay": WEIGHT_DECAY,
            "label_smoothing": LABEL_SMOOTHING,
            "freeze_backbone_epochs": FREEZE_BACKBONE_EPOCHS,
            "patience": PATIENCE,
            "device": str(DEVICE),
            "model": "vit_b_16_improved",
            "use_tta": USE_TTA,
            "use_mixup": USE_MIXUP,
            "mixup_alpha": MIXUP_ALPHA,
            "ema_decay": EMA_DECAY,
            "grad_clip_norm": GRAD_CLIP_NORM,
        },
        "num_train": len(train_dataset),
        "num_test": len(test_eval_dataset),
        "num_classes": num_classes,
        "classes": train_dataset.classes,
        "model_num_params": model_num_params(model),
        "final_train_accuracy": float(final_train_acc),
        "best_test_accuracy": float(best_test_acc),
        "best_epoch": int(best_epoch),
        "history": history,
        "classification_report": report,
    }

    save_json(metrics, seed_output_dir / "metrics.json")
    torch.save({
        "model_state_dict": best_state_dict,
        "ema_state_dict": best_ema_state_dict,
        "classes": train_dataset.classes,
        "best_epoch": best_epoch,
        "best_test_accuracy": best_test_acc,
        "seed": seed,
    }, seed_output_dir / "best_model.pt")

    return {
        "seed": seed,
        "best_test_accuracy": float(best_test_acc),
        "best_epoch": int(best_epoch),
        "final_train_accuracy": float(final_train_acc),
        "logits_path": str(seed_output_dir / "best_test_logits.npy"),
        "csv_path": str(seed_output_dir / "best_test_predictions.csv"),
    }


# =========================================================
# 11. Train all 3 seeds
# =========================================================
seed_summaries = []
all_seed_logits = []
reference_file_names = None

for seed in SEEDS:
    summary = train_one_seed(seed)
    seed_summaries.append(summary)

    logits = np.load(summary["logits_path"])
    all_seed_logits.append(logits)

    # recover file order from one of the saved CSVs
    pred_df = pd.read_csv(summary["csv_path"])
    file_names = pred_df["file_name"].tolist()

    if reference_file_names is None:
        reference_file_names = file_names
    else:
        if reference_file_names != file_names:
            raise ValueError("File order mismatch across seeds. Cannot ensemble safely.")


# =========================================================
# 12. Ensemble logits and save final submission
# =========================================================
ensemble_logits = np.mean(np.stack(all_seed_logits, axis=0), axis=0)
ensemble_pred_df = logits_to_pred_df(ensemble_logits, reference_file_names, idx_to_class)
ensemble_pred_df.to_csv(OUTPUT_ENSEMBLE_CSV, index=False)

# evaluate ensemble on solution.csv
solution_df = pd.read_csv(SOLUTION_CSV)
solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))
y_true_labels = [solution_map[f] for f in reference_file_names]
y_pred_labels = ensemble_pred_df["label"].tolist()
ensemble_test_acc = float(np.mean(np.array(y_true_labels) == np.array(y_pred_labels)))

summary = {
    "seeds": SEEDS,
    "seed_summaries": seed_summaries,
    "ensemble_test_accuracy": ensemble_test_acc,
    "ensemble_csv": str(OUTPUT_ENSEMBLE_CSV),
}

save_json(summary, OUTPUT_SUMMARY_JSON)

print("\n==== Final Ensemble Results ====")
for row in seed_summaries:
    print(
        f"seed={row['seed']} "
        f"train={row['final_train_accuracy']:.4f} "
        f"test={row['best_test_accuracy']:.4f} "
        f"best_epoch={row['best_epoch']}"
    )

print(f"ensemble_test_accuracy={ensemble_test_acc:.4f}")
print(f"Saved ensemble metrics to {OUTPUT_SUMMARY_JSON}")
print(f"Saved final ensemble submission to {OUTPUT_ENSEMBLE_CSV}")

ensemble_pred_df.head()

Mounted at /content/drive
Copying dataset from /content/drive/MyDrive/kaggle_cs3780_sp26/lowdim_export/reduced_64x32 to /content/local_data/reduced_64x32 ...
Copy complete.
Local train dir: /content/local_data/reduced_64x32/train
Local test dir: /content/local_data/reduced_64x32/test
Local solution: /content/local_data/reduced_64x32/solution.csv
Using device: cuda
GPU: NVIDIA A100-SXM4-40GB
num_classes = 9
num_train = 21898
num_test = 5454

================================================================================
Starting seed 2026
Downloading: "https://download.pytorch.org/models/vit_b_16-c867db91.pth" to /root/.cache/torch/hub/checkpoints/vit_b_16-c867db91.pth

100%|██████████| 330M/330M [00:01<00:00, 234MB/s]

[seed 2026] Epoch 1/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.9777, train_acc=0.2508
[seed 2026] test_loss=2.0125, test_acc=0.2921, lr=0.0005

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 1

[seed 2026] Epoch 2/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.9450, train_acc=0.2654
[seed 2026] test_loss=1.9179, test_acc=0.3359, lr=0.001

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 2
[seed 2026] Unfreezing full backbone at epoch 3

[seed 2026] Epoch 3/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.8517, train_acc=0.2840
[seed 2026] test_loss=1.8146, test_acc=0.3893, lr=2e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 3

[seed 2026] Epoch 4/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.7386, train_acc=0.3209
[seed 2026] test_loss=1.7026, test_acc=0.4402, lr=2e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 4

[seed 2026] Epoch 5/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.6795, train_acc=0.3473
[seed 2026] test_loss=1.6241, test_acc=0.4787, lr=1.98481e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 5

[seed 2026] Epoch 6/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.6394, train_acc=0.3457
[seed 2026] test_loss=1.5741, test_acc=0.5066, lr=1.93247e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 6

[seed 2026] Epoch 7/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.5901, train_acc=0.3666
[seed 2026] test_loss=1.5424, test_acc=0.5207, lr=1.83147e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 7

[seed 2026] Epoch 8/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.5491, train_acc=0.3756
[seed 2026] test_loss=1.5217, test_acc=0.5350, lr=1.66913e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 8

[seed 2026] Epoch 9/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.4948, train_acc=0.3873
[seed 2026] test_loss=1.5103, test_acc=0.5374, lr=1.43388e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 9

[seed 2026] Epoch 10/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.4444, train_acc=0.3909
[seed 2026] test_loss=1.5101, test_acc=0.5447, lr=1.12054e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 10

[seed 2026] Epoch 11/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.3832, train_acc=0.4220
[seed 2026] test_loss=1.5168, test_acc=0.5424, lr=7.41181e-06

[seed 2026] Epoch 12/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.3418, train_acc=0.4505
[seed 2026] test_loss=1.5294, test_acc=0.5425, lr=3.45139e-06

[seed 2026] Epoch 13/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.2924, train_acc=0.4418
[seed 2026] test_loss=1.5430, test_acc=0.5396, lr=4.89435e-07

[seed 2026] Epoch 14/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.3065, train_acc=0.4484
[seed 2026] test_loss=1.5529, test_acc=0.5387, lr=6.03074e-07

[seed 2026] Epoch 15/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.3388, train_acc=0.4320
[seed 2026] test_loss=1.5540, test_acc=0.5392, lr=6.17317e-06

[seed 2026] Epoch 16/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2026] train_loss=1.3582, train_acc=0.4210
[seed 2026] test_loss=1.5503, test_acc=0.5416, lr=1.62349e-05
[seed 2026] Early stopping after 6 epochs without improvement.

  0%|          | 0/685 [00:00<?, ?it/s]

================================================================================
Starting seed 2027

[seed 2027] Epoch 1/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.9756, train_acc=0.2593
[seed 2027] test_loss=2.0207, test_acc=0.2835, lr=0.0005

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 1

[seed 2027] Epoch 2/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.9470, train_acc=0.2610
[seed 2027] test_loss=1.9200, test_acc=0.3535, lr=0.001

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 2
[seed 2027] Unfreezing full backbone at epoch 3

[seed 2027] Epoch 3/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.8559, train_acc=0.2854
[seed 2027] test_loss=1.8164, test_acc=0.3929, lr=2e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 3

[seed 2027] Epoch 4/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.7314, train_acc=0.3234
[seed 2027] test_loss=1.7061, test_acc=0.4380, lr=2e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 4

[seed 2027] Epoch 5/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.6885, train_acc=0.3373
[seed 2027] test_loss=1.6282, test_acc=0.4763, lr=1.98481e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 5

[seed 2027] Epoch 6/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.6313, train_acc=0.3497
[seed 2027] test_loss=1.5768, test_acc=0.5068, lr=1.93247e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 6

[seed 2027] Epoch 7/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.5874, train_acc=0.3611
[seed 2027] test_loss=1.5408, test_acc=0.5288, lr=1.83147e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 7

[seed 2027] Epoch 8/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.5360, train_acc=0.3699
[seed 2027] test_loss=1.5188, test_acc=0.5400, lr=1.66913e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 8

[seed 2027] Epoch 9/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.4997, train_acc=0.3816
[seed 2027] test_loss=1.5063, test_acc=0.5468, lr=1.43388e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 9

[seed 2027] Epoch 10/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.4517, train_acc=0.4034
[seed 2027] test_loss=1.5045, test_acc=0.5479, lr=1.12054e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 10

[seed 2027] Epoch 11/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.3924, train_acc=0.4112
[seed 2027] test_loss=1.5125, test_acc=0.5449, lr=7.41181e-06

[seed 2027] Epoch 12/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.3375, train_acc=0.4380
[seed 2027] test_loss=1.5261, test_acc=0.5480, lr=3.45139e-06

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 12

[seed 2027] Epoch 13/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.3033, train_acc=0.4506
[seed 2027] test_loss=1.5403, test_acc=0.5469, lr=4.89435e-07

[seed 2027] Epoch 14/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.3161, train_acc=0.4485
[seed 2027] test_loss=1.5509, test_acc=0.5455, lr=6.03074e-07

[seed 2027] Epoch 15/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.3144, train_acc=0.4413
[seed 2027] test_loss=1.5547, test_acc=0.5451, lr=6.17317e-06

[seed 2027] Epoch 16/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.3969, train_acc=0.4296
[seed 2027] test_loss=1.5460, test_acc=0.5440, lr=1.62349e-05

[seed 2027] Epoch 17/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.3751, train_acc=0.4340
[seed 2027] test_loss=1.5400, test_acc=0.5477, lr=1.86603e-05

[seed 2027] Epoch 18/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2027] train_loss=1.2624, train_acc=0.4524
[seed 2027] test_loss=1.5563, test_acc=0.5403, lr=1.90983e-06
[seed 2027] Early stopping after 6 epochs without improvement.

  0%|          | 0/685 [00:00<?, ?it/s]

================================================================================
Starting seed 2028

[seed 2028] Epoch 1/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.9723, train_acc=0.2549
[seed 2028] test_loss=2.0321, test_acc=0.2629, lr=0.0005

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 1

[seed 2028] Epoch 2/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.9447, train_acc=0.2582
[seed 2028] test_loss=1.9219, test_acc=0.3361, lr=0.001

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 2
[seed 2028] Unfreezing full backbone at epoch 3

[seed 2028] Epoch 3/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.8495, train_acc=0.2910
[seed 2028] test_loss=1.8153, test_acc=0.3931, lr=2e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 3

[seed 2028] Epoch 4/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.7439, train_acc=0.3279
[seed 2028] test_loss=1.7052, test_acc=0.4404, lr=2e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 4

[seed 2028] Epoch 5/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.6971, train_acc=0.3291
[seed 2028] test_loss=1.6277, test_acc=0.4763, lr=1.98481e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 5

[seed 2028] Epoch 6/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.6333, train_acc=0.3454
[seed 2028] test_loss=1.5758, test_acc=0.5035, lr=1.93247e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 6

[seed 2028] Epoch 7/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.5950, train_acc=0.3550
[seed 2028] test_loss=1.5422, test_acc=0.5233, lr=1.83147e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 7

[seed 2028] Epoch 8/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.5548, train_acc=0.3736
[seed 2028] test_loss=1.5223, test_acc=0.5348, lr=1.66913e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 8

[seed 2028] Epoch 9/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.4870, train_acc=0.3832
[seed 2028] test_loss=1.5106, test_acc=0.5446, lr=1.43388e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 9

[seed 2028] Epoch 10/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.4399, train_acc=0.4133
[seed 2028] test_loss=1.5078, test_acc=0.5464, lr=1.12054e-05

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 10

[seed 2028] Epoch 11/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.3883, train_acc=0.4129
[seed 2028] test_loss=1.5144, test_acc=0.5469, lr=7.41181e-06

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 11

[seed 2028] Epoch 12/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.3436, train_acc=0.4199
[seed 2028] test_loss=1.5236, test_acc=0.5477, lr=3.45139e-06

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 12

[seed 2028] Epoch 13/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.3169, train_acc=0.4368
[seed 2028] test_loss=1.5352, test_acc=0.5453, lr=4.89435e-07

[seed 2028] Epoch 14/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.3064, train_acc=0.4443
[seed 2028] test_loss=1.5440, test_acc=0.5431, lr=6.03074e-07

[seed 2028] Epoch 15/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.3153, train_acc=0.4463
[seed 2028] test_loss=1.5452, test_acc=0.5413, lr=6.17317e-06

[seed 2028] Epoch 16/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.3896, train_acc=0.4126
[seed 2028] test_loss=1.5378, test_acc=0.5453, lr=1.62349e-05

[seed 2028] Epoch 17/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.3669, train_acc=0.4109
[seed 2028] test_loss=1.5352, test_acc=0.5444, lr=1.86603e-05

[seed 2028] Epoch 18/22

  0%|          | 0/685 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

[seed 2028] train_loss=1.2610, train_acc=0.4557
[seed 2028] test_loss=1.5481, test_acc=0.5438, lr=1.90983e-06
[seed 2028] Early stopping after 6 epochs without improvement.

  0%|          | 0/685 [00:00<?, ?it/s]

==== Final Ensemble Results ====
seed=2026 train=0.6942 test=0.5447 best_epoch=10
seed=2027 train=0.7458 test=0.5480 best_epoch=12
seed=2028 train=0.7484 test=0.5477 best_epoch=12
ensemble_test_accuracy=0.5578
Saved ensemble metrics to /content/drive/MyDrive/kaggle_cs3780_sp26/vit_b_16_3seed_ensemble_new/vit_b_16_3seed_ensemble_new_metrics.json
Saved final ensemble submission to /content/drive/MyDrive/kaggle_cs3780_sp26/vit_b_16_3seed_ensemble_new/vit_b_16_3seed_ensemble_new_submission.csv

  file_name                  label
0     1.png         Nocturnal bird
1    10.png  Water-associated bird
2   100.png             Flycatcher
3  1000.png         Nocturnal bird
4  1001.png             Flycatcher

pre-trained spectrogram model

In [ ]:
!pip -q install transformers accelerate scikit-learn

In [ ]:
import copy
import json
import math
import random
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image

from sklearn.metrics import accuracy_score, classification_report

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from tqdm.auto import tqdm

from transformers import ASTForAudioClassification


# =========================================================
# 1. Mount Drive and copy dataset to local disk
# =========================================================
from google.colab import drive
drive.mount("/content/drive")

DRIVE_ROOT = Path("/content/drive/MyDrive/kaggle_cs3780_sp26")
DRIVE_DATA_DIR = DRIVE_ROOT / "lowdim_export" / "reduced_64x32"
LOCAL_ROOT = Path("/content/local_data")
LOCAL_DATA_DIR = LOCAL_ROOT / "reduced_64x32"

if LOCAL_DATA_DIR.exists():
    print(f"Local dataset already exists at {LOCAL_DATA_DIR}")
else:
    LOCAL_ROOT.mkdir(parents=True, exist_ok=True)
    print(f"Copying dataset from {DRIVE_DATA_DIR} to {LOCAL_DATA_DIR} ...")
    shutil.copytree(DRIVE_DATA_DIR, LOCAL_DATA_DIR)
    print("Copy complete.")

print("Local train dir:", LOCAL_DATA_DIR / "train")
print("Local test dir:", LOCAL_DATA_DIR / "test")
print("Local solution:", LOCAL_DATA_DIR / "solution.csv")


# =========================================================
# 2. Config
# =========================================================
BASE_DATA_ROOT = LOCAL_ROOT
TRAIN_SUBDIR = Path("reduced_64x32/train")
TEST_SUBDIR = Path("reduced_64x32/test")
SOLUTION_CSV = LOCAL_DATA_DIR / "solution.csv"

OUTPUT_DIR = DRIVE_ROOT / "ast_png_spectrogram"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_SUMMARY_JSON = OUTPUT_DIR / "ast_png_spectrogram_metrics.json"
OUTPUT_ENSEMBLE_CSV = OUTPUT_DIR / "ast_png_spectrogram_submission.csv"

# AST pretrained defaults are max_length=1024 and num_mel_bins=128.
# We adapt the PNG spectrograms to that shape.
AST_TIME_BINS = 1024   # width / temporal dimension
AST_MEL_BINS = 128     # height / frequency dimension

BATCH_SIZE = 8
EPOCHS = 12
WARMUP_EPOCHS = 1

LR_HEAD = 1e-4
LR_BACKBONE = 1e-5
WEIGHT_DECAY = 1e-4
LABEL_SMOOTHING = 0.05
FREEZE_BACKBONE_EPOCHS = 1

NUM_WORKERS = 2
PATIENCE = 4
USE_AMP = True
GRAD_CLIP_NORM = 1.0
EMA_DECAY = 0.999

SEEDS = [2026, 2027, 2028]

MODEL_NAME = "MIT/ast-finetuned-audioset-10-10-0.4593"

# If your spectrogram images have dark background + bright signal, keep False first.
# If performance is bad, try True once.
INVERT_SPEC = False


# =========================================================
# 3. Utilities
# =========================================================
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
PIN_MEMORY = torch.cuda.is_available()

print("Using device:", DEVICE)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))


def save_json(obj, path: Path):
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)


def model_num_params(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters())


# =========================================================
# 4. Spectrogram PNG -> AST input
# =========================================================
def png_to_ast_input(
    img: Image.Image,
    time_bins: int = AST_TIME_BINS,
    mel_bins: int = AST_MEL_BINS,
    invert_spec: bool = INVERT_SPEC,
    train: bool = False,
) -> torch.Tensor:
    """
    Convert a PNG spectrogram into AST input_values of shape (time_bins, mel_bins).

    AST expects input_values shaped (batch, max_length, num_mel_bins),
    i.e. (time, mel) per example.

    We only have rendered PNGs, so we:
      1) convert to grayscale
      2) resize to AST expected spectrogram size
      3) optionally do light augmentation
      4) standardize per-image
    """
    img = img.convert("L")  # grayscale

    # Resize so height = mel bins, width = time bins
    img = img.resize((time_bins, mel_bins), resample=Image.BILINEAR)

    arr = np.array(img).astype(np.float32) / 255.0

    if invert_spec:
        arr = 1.0 - arr

    if train:
        # small horizontal/vertical jitter by rolling
        if random.random() < 0.5:
            shift = random.randint(-8, 8)
            arr = np.roll(arr, shift=shift, axis=1)  # time axis
        if random.random() < 0.3:
            shift = random.randint(-2, 2)
            arr = np.roll(arr, shift=shift, axis=0)  # freq axis

        # simple masking, inspired by SpecAugment
        if random.random() < 0.5:
            t = random.randint(8, 48)
            t0 = random.randint(0, max(0, time_bins - t))
            arr[:, t0:t0+t] = 0.0

        if random.random() < 0.5:
            f = random.randint(4, 16)
            f0 = random.randint(0, max(0, mel_bins - f))
            arr[f0:f0+f, :] = 0.0

    # Per-image standardization
    mean = arr.mean()
    std = arr.std()
    arr = (arr - mean) / (std + 1e-6)

    # AST wants (time, mel), but image is currently (mel, time)
    arr = arr.T  # -> (time_bins, mel_bins)

    return torch.tensor(arr, dtype=torch.float32)


# =========================================================
# 5. Dataset
# =========================================================
class TrainFolderASTDataset(Dataset):
    def __init__(self, root_dir: Path, train: bool = False):
        self.root_dir = root_dir
        self.train = train

        self.classes = sorted([p.name for p in root_dir.iterdir() if p.is_dir()])
        if not self.classes:
            raise FileNotFoundError(f"No class folders found under {root_dir}")

        self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}
        self.idx_to_class = {i: cls_name for cls_name, i in self.class_to_idx.items()}

        self.samples = []
        for cls_name in self.classes:
            class_dir = root_dir / cls_name
            for img_path in sorted(class_dir.rglob("*.png")):
                self.samples.append((img_path, self.class_to_idx[cls_name]))

        if not self.samples:
            raise FileNotFoundError(f"No PNG files found under {root_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            x = png_to_ast_input(img, train=self.train)
        return x, label


class TestWithSolutionASTDataset(Dataset):
    def __init__(self, test_dir: Path, solution_csv: Path, class_to_idx: dict[str, int]):
        self.test_dir = test_dir
        self.class_to_idx = class_to_idx

        solution_df = pd.read_csv(solution_csv)
        if "file_name" not in solution_df.columns or "label" not in solution_df.columns:
            raise ValueError("solution.csv must contain columns: file_name, label")

        solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))

        self.samples = []
        image_paths = sorted(test_dir.rglob("*.png"))
        if not image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

        for img_path in image_paths:
            fname = img_path.name
            if fname not in solution_map:
                raise KeyError(f"{fname} not found in solution.csv")
            label_name = solution_map[fname]
            if label_name not in class_to_idx:
                raise KeyError(f"Label {label_name} from solution.csv not found in training classes")
            label_idx = class_to_idx[label_name]
            self.samples.append((img_path, label_idx))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            x = png_to_ast_input(img, train=False)
        return x, label, img_path.name


class TestUnlabeledASTDataset(Dataset):
    def __init__(self, test_dir: Path):
        self.test_dir = test_dir
        self.image_paths = sorted(test_dir.rglob("*.png"))
        if not self.image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        with Image.open(img_path) as img:
            x = png_to_ast_input(img, train=False)
        return x, img_path.name


# =========================================================
# 6. Load data
# =========================================================
train_dir = BASE_DATA_ROOT / TRAIN_SUBDIR
test_dir = BASE_DATA_ROOT / TEST_SUBDIR

base_train_dataset = TrainFolderASTDataset(train_dir, train=True)
test_eval_dataset = TestWithSolutionASTDataset(
    test_dir=test_dir,
    solution_csv=SOLUTION_CSV,
    class_to_idx=base_train_dataset.class_to_idx,
)
test_pred_dataset = TestUnlabeledASTDataset(test_dir=test_dir)
train_eval_dataset = TrainFolderASTDataset(train_dir, train=False)

persistent = NUM_WORKERS > 0

test_eval_loader = DataLoader(
    test_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

test_pred_loader = DataLoader(
    test_pred_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

train_eval_loader = DataLoader(
    train_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

num_classes = len(base_train_dataset.classes)
idx_to_class = base_train_dataset.idx_to_class

print("num_classes =", num_classes)
print("num_train =", len(base_train_dataset))
print("num_test =", len(test_eval_dataset))


# =========================================================
# 7. Model / EMA
# =========================================================
def build_model(num_classes: int):
    model = ASTForAudioClassification.from_pretrained(
        MODEL_NAME,
        num_labels=num_classes,
        ignore_mismatched_sizes=True,
    )
    return model


def freeze_backbone_except_head(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False
    for p in model.classifier.parameters():
        p.requires_grad = True


def unfreeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = True


class ModelEMA:
    def __init__(self, model, decay=0.999):
        self.decay = decay
        self.ema = copy.deepcopy(model).eval()
        for p in self.ema.parameters():
            p.requires_grad = False

    @torch.no_grad()
    def update(self, model):
        msd = model.state_dict()
        for k, v in self.ema.state_dict().items():
            if v.dtype.is_floating_point:
                v.copy_(v * self.decay + msd[k].detach() * (1.0 - self.decay))
            else:
                v.copy_(msd[k])


# =========================================================
# 8. Scheduler
# =========================================================
def cosine_lr_lambda(current_epoch, total_epochs, warmup_epochs):
    if current_epoch < warmup_epochs:
        return float(current_epoch + 1) / float(max(1, warmup_epochs))
    progress = (current_epoch - warmup_epochs) / float(max(1, total_epochs - warmup_epochs))
    return 0.5 * (1.0 + math.cos(math.pi * progress))


def make_optimizer(model, lr):
    return torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=lr,
        weight_decay=WEIGHT_DECAY,
    )


# =========================================================
# 9. Train / Eval / Predict
# =========================================================
@torch.no_grad()
def run_eval_epoch(eval_model, loader, criterion, device, use_amp=True):
    eval_model.eval()
    total_loss = 0.0
    all_preds = []
    all_labels = []
    all_file_names = []

    use_amp = use_amp and device.type == "cuda"

    for batch in tqdm(loader, leave=False):
        if len(batch) == 3:
            input_values, labels, file_names = batch
            all_file_names.extend(file_names)
        else:
            input_values, labels = batch

        input_values = input_values.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            outputs = eval_model(input_values=input_values)
            logits = outputs.logits
            loss = criterion(logits, labels)

        total_loss += loss.item() * input_values.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc, np.array(all_labels), np.array(all_preds), all_file_names


def run_train_epoch(model, ema_model, loader, criterion, optimizer, scaler, device, use_amp=True):
    model.train()
    total_loss = 0.0
    all_preds = []
    all_labels = []

    use_amp = use_amp and device.type == "cuda"

    for input_values, labels in tqdm(loader, leave=False):
        input_values = input_values.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            outputs = model(input_values=input_values)
            logits = outputs.logits
            loss = criterion(logits, labels)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
        scaler.step(optimizer)
        scaler.update()

        ema_model.update(model)

        total_loss += loss.item() * input_values.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc


@torch.no_grad()
def predict_logits(eval_model, loader, device, use_amp=True):
    eval_model.eval()
    all_logits = []
    all_file_names = []
    use_amp = use_amp and device.type == "cuda"

    for input_values, file_names in tqdm(loader, leave=False):
        input_values = input_values.to(device, non_blocking=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            outputs = eval_model(input_values=input_values)
            logits = outputs.logits

        all_logits.append(logits.float().cpu())
        all_file_names.extend(list(file_names))

    all_logits = torch.cat(all_logits, dim=0).numpy()
    return all_logits, all_file_names


def logits_to_pred_df(logits: np.ndarray, file_names: list[str], idx_to_class: dict[int, str]):
    preds = logits.argmax(axis=1)
    if len(preds) != len(file_names):
        raise ValueError(f"Length mismatch: {len(preds)=}, {len(file_names)=}")
    return pd.DataFrame({
        "file_name": file_names,
        "label": [idx_to_class[int(i)] for i in preds],
    })


# =========================================================
# 10. One seed training
# =========================================================
def train_one_seed(seed: int):
    print("\n" + "=" * 80)
    print(f"Starting seed {seed}")
    set_seed(seed)

    seed_output_dir = OUTPUT_DIR / f"seed_{seed}"
    seed_output_dir.mkdir(parents=True, exist_ok=True)

    train_dataset = TrainFolderASTDataset(train_dir, train=True)
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=persistent,
    )

    model = build_model(num_classes).to(DEVICE)
    ema_model = ModelEMA(model, decay=EMA_DECAY)

    criterion = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)

    freeze_backbone_except_head(model)
    optimizer = make_optimizer(model, LR_HEAD)

    scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and DEVICE.type == "cuda"))
    scheduler = torch.optim.lr_scheduler.LambdaLR(
        optimizer,
        lr_lambda=lambda epoch: cosine_lr_lambda(epoch, EPOCHS, WARMUP_EPOCHS)
    )

    history = []
    best_test_acc = -1.0
    best_epoch = -1
    best_state_dict = None
    best_ema_state_dict = None
    best_y_true = None
    best_y_pred = None
    epochs_without_improve = 0

    for epoch in range(1, EPOCHS + 1):
        if epoch == FREEZE_BACKBONE_EPOCHS + 1 and FREEZE_BACKBONE_EPOCHS > 0:
            print(f"[seed {seed}] Unfreezing full backbone at epoch {epoch}")
            unfreeze_all(model)
            optimizer = make_optimizer(model, LR_BACKBONE)
            scheduler = torch.optim.lr_scheduler.LambdaLR(
                optimizer,
                lr_lambda=lambda ep: cosine_lr_lambda(ep, max(EPOCHS - epoch + 1, 1), 1)
            )

        print(f"\n[seed {seed}] Epoch {epoch}/{EPOCHS}")

        train_loss, train_acc = run_train_epoch(
            model, ema_model, train_loader, criterion, optimizer, scaler, DEVICE, USE_AMP
        )

        test_loss, test_acc, y_true, y_pred, _ = run_eval_epoch(
            ema_model.ema, test_eval_loader, criterion, DEVICE, USE_AMP
        )

        print(f"[seed {seed}] train_loss={train_loss:.4f}, train_acc={train_acc:.4f}")
        print(f"[seed {seed}] test_loss={test_loss:.4f}, test_acc={test_acc:.4f}, lr={optimizer.param_groups[0]['lr']:.6g}")

        history.append({
            "epoch": epoch,
            "train_loss": float(train_loss),
            "train_accuracy": float(train_acc),
            "test_loss": float(test_loss),
            "test_accuracy": float(test_acc),
            "lr": float(optimizer.param_groups[0]["lr"]),
        })

        if test_acc > best_test_acc:
            best_test_acc = test_acc
            best_epoch = epoch
            best_state_dict = copy.deepcopy(model.state_dict())
            best_ema_state_dict = copy.deepcopy(ema_model.ema.state_dict())
            best_y_true = y_true.copy()
            best_y_pred = y_pred.copy()
            epochs_without_improve = 0

            best_logits, best_file_names = predict_logits(
                ema_model.ema,
                test_pred_loader,
                DEVICE,
                use_amp=USE_AMP,
            )
            best_pred_df = logits_to_pred_df(best_logits, best_file_names, idx_to_class)
            best_pred_df.to_csv(seed_output_dir / "best_test_predictions.csv", index=False)
            np.save(seed_output_dir / "best_test_logits.npy", best_logits)
            print(f"[seed {seed}] Saved new best logits/CSV at epoch {epoch}")
        else:
            epochs_without_improve += 1

        scheduler.step()

        if epochs_without_improve >= PATIENCE:
            print(f"[seed {seed}] Early stopping after {PATIENCE} epochs without improvement.")
            break

    ema_model.ema.load_state_dict(best_ema_state_dict)

    final_train_loss, final_train_acc, _, _, _ = run_eval_epoch(
        ema_model.ema, train_eval_loader, criterion, DEVICE, USE_AMP
    )

    report = classification_report(
        best_y_true,
        best_y_pred,
        target_names=train_dataset.classes,
        output_dict=True,
        zero_division=0,
    )

    metrics = {
        "seed": seed,
        "config": {
            "model_name": MODEL_NAME,
            "ast_time_bins": AST_TIME_BINS,
            "ast_mel_bins": AST_MEL_BINS,
            "batch_size": BATCH_SIZE,
            "epochs": EPOCHS,
            "warmup_epochs": WARMUP_EPOCHS,
            "lr_head": LR_HEAD,
            "lr_backbone": LR_BACKBONE,
            "weight_decay": WEIGHT_DECAY,
            "label_smoothing": LABEL_SMOOTHING,
            "freeze_backbone_epochs": FREEZE_BACKBONE_EPOCHS,
            "patience": PATIENCE,
            "device": str(DEVICE),
            "invert_spec": INVERT_SPEC,
            "ema_decay": EMA_DECAY,
            "grad_clip_norm": GRAD_CLIP_NORM,
        },
        "num_train": len(train_dataset),
        "num_test": len(test_eval_dataset),
        "num_classes": num_classes,
        "classes": train_dataset.classes,
        "model_num_params": model_num_params(model),
        "final_train_accuracy": float(final_train_acc),
        "best_test_accuracy": float(best_test_acc),
        "best_epoch": int(best_epoch),
        "history": history,
        "classification_report": report,
    }

    save_json(metrics, seed_output_dir / "metrics.json")
    torch.save({
        "model_state_dict": best_state_dict,
        "ema_state_dict": best_ema_state_dict,
        "classes": train_dataset.classes,
        "best_epoch": best_epoch,
        "best_test_accuracy": best_test_acc,
        "seed": seed,
    }, seed_output_dir / "best_model.pt")

    return {
        "seed": seed,
        "best_test_accuracy": float(best_test_acc),
        "best_epoch": int(best_epoch),
        "final_train_accuracy": float(final_train_acc),
        "logits_path": str(seed_output_dir / "best_test_logits.npy"),
        "csv_path": str(seed_output_dir / "best_test_predictions.csv"),
    }


# =========================================================
# 11. Train all seeds
# =========================================================
seed_summaries = []
all_seed_logits = []
reference_file_names = None

for seed in SEEDS:
    summary = train_one_seed(seed)
    seed_summaries.append(summary)

    logits = np.load(summary["logits_path"])
    all_seed_logits.append(logits)

    pred_df = pd.read_csv(summary["csv_path"])
    file_names = pred_df["file_name"].tolist()

    if reference_file_names is None:
        reference_file_names = file_names
    else:
        if reference_file_names != file_names:
            raise ValueError("File order mismatch across seeds. Cannot ensemble safely.")


# =========================================================
# 12. Ensemble and save
# =========================================================
ensemble_logits = np.mean(np.stack(all_seed_logits, axis=0), axis=0)
ensemble_pred_df = logits_to_pred_df(ensemble_logits, reference_file_names, idx_to_class)
ensemble_pred_df.to_csv(OUTPUT_ENSEMBLE_CSV, index=False)

solution_df = pd.read_csv(SOLUTION_CSV)
solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))
y_true_labels = [solution_map[f] for f in reference_file_names]
y_pred_labels = ensemble_pred_df["label"].tolist()
ensemble_test_acc = float(np.mean(np.array(y_true_labels) == np.array(y_pred_labels)))

summary = {
    "seeds": SEEDS,
    "seed_summaries": seed_summaries,
    "ensemble_test_accuracy": ensemble_test_acc,
    "ensemble_csv": str(OUTPUT_ENSEMBLE_CSV),
}

save_json(summary, OUTPUT_SUMMARY_JSON)

print("\n==== Final Ensemble Results ====")
for row in seed_summaries:
    print(
        f"seed={row['seed']} "
        f"train={row['final_train_accuracy']:.4f} "
        f"test={row['best_test_accuracy']:.4f} "
        f"best_epoch={row['best_epoch']}"
    )

print(f"ensemble_test_accuracy={ensemble_test_acc:.4f}")
print(f"Saved ensemble metrics to {OUTPUT_SUMMARY_JSON}")
print(f"Saved final ensemble submission to {OUTPUT_ENSEMBLE_CSV}")

ensemble_pred_df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Local dataset already exists at /content/local_data/reduced_64x32
Local train dir: /content/local_data/reduced_64x32/train
Local test dir: /content/local_data/reduced_64x32/test
Local solution: /content/local_data/reduced_64x32/solution.csv
Using device: cuda
GPU: NVIDIA A100-SXM4-40GB
num_classes = 9
num_train = 21898
num_test = 5454

================================================================================
Starting seed 2026

Loading weights:   0%|          | 0/203 [00:00<?, ?it/s]

ASTForAudioClassification LOAD REPORT from: MIT/ast-finetuned-audioset-10-10-0.4593
Key                     | Status   |
------------------------+----------+---------------------------------------------------------------------------------------
classifier.dense.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([527, 768]) vs model:torch.Size([9, 768])
classifier.dense.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([527]) vs model:torch.Size([9])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

[seed 2026] Epoch 1/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.9564, train_acc=0.2908
[seed 2026] test_loss=1.9331, test_acc=0.2899, lr=0.0001

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 1
[seed 2026] Unfreezing full backbone at epoch 2

[seed 2026] Epoch 2/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.7855, train_acc=0.3788
[seed 2026] test_loss=1.6644, test_acc=0.4353, lr=1e-05

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 2

[seed 2026] Epoch 3/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.5924, train_acc=0.4646
[seed 2026] test_loss=1.5048, test_acc=0.5086, lr=1e-05

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 3

[seed 2026] Epoch 4/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.4756, train_acc=0.5169
[seed 2026] test_loss=1.4362, test_acc=0.5363, lr=9.69846e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 4

[seed 2026] Epoch 5/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.3722, train_acc=0.5545
[seed 2026] test_loss=1.3959, test_acc=0.5550, lr=8.53553e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 5

[seed 2026] Epoch 6/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.2451, train_acc=0.6102
[seed 2026] test_loss=1.3932, test_acc=0.5655, lr=6.1126e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 6

[seed 2026] Epoch 7/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.0971, train_acc=0.6737
[seed 2026] test_loss=1.4133, test_acc=0.5704, lr=2.5e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 7

[seed 2026] Epoch 8/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.0224, train_acc=0.7061
[seed 2026] test_loss=1.4320, test_acc=0.5656, lr=0

[seed 2026] Epoch 9/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.0808, train_acc=0.6829
[seed 2026] test_loss=1.4327, test_acc=0.5699, lr=5e-06

[seed 2026] Epoch 10/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.0577, train_acc=0.6905
[seed 2026] test_loss=1.4460, test_acc=0.5719, lr=7.5e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] Saved new best logits/CSV at epoch 10

[seed 2026] Epoch 11/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=1.0297, train_acc=0.6968
[seed 2026] test_loss=1.4736, test_acc=0.5666, lr=1e-05

[seed 2026] Epoch 12/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2026] train_loss=0.9237, train_acc=0.7408
[seed 2026] test_loss=1.5565, test_acc=0.5468, lr=0

  0%|          | 0/2738 [00:00<?, ?it/s]

================================================================================
Starting seed 2027

Loading weights:   0%|          | 0/203 [00:00<?, ?it/s]

ASTForAudioClassification LOAD REPORT from: MIT/ast-finetuned-audioset-10-10-0.4593
Key                     | Status   |
------------------------+----------+---------------------------------------------------------------------------------------
classifier.dense.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([527, 768]) vs model:torch.Size([9, 768])
classifier.dense.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([527]) vs model:torch.Size([9])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

[seed 2027] Epoch 1/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.9505, train_acc=0.2945
[seed 2027] test_loss=1.9362, test_acc=0.2935, lr=0.0001

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 1
[seed 2027] Unfreezing full backbone at epoch 2

[seed 2027] Epoch 2/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.7863, train_acc=0.3819
[seed 2027] test_loss=1.6680, test_acc=0.4316, lr=1e-05

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 2

[seed 2027] Epoch 3/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.5881, train_acc=0.4643
[seed 2027] test_loss=1.5091, test_acc=0.5048, lr=1e-05

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 3

[seed 2027] Epoch 4/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.4729, train_acc=0.5138
[seed 2027] test_loss=1.4357, test_acc=0.5372, lr=9.69846e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 4

[seed 2027] Epoch 5/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.3683, train_acc=0.5575
[seed 2027] test_loss=1.3971, test_acc=0.5510, lr=8.53553e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 5

[seed 2027] Epoch 6/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.2450, train_acc=0.6101
[seed 2027] test_loss=1.3974, test_acc=0.5614, lr=6.1126e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 6

[seed 2027] Epoch 7/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.0965, train_acc=0.6755
[seed 2027] test_loss=1.4184, test_acc=0.5618, lr=2.5e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 7

[seed 2027] Epoch 8/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.0113, train_acc=0.7111
[seed 2027] test_loss=1.4309, test_acc=0.5563, lr=0

[seed 2027] Epoch 9/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.0768, train_acc=0.6823
[seed 2027] test_loss=1.4295, test_acc=0.5647, lr=5e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] Saved new best logits/CSV at epoch 9

[seed 2027] Epoch 10/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.0597, train_acc=0.6848
[seed 2027] test_loss=1.4451, test_acc=0.5625, lr=7.5e-06

[seed 2027] Epoch 11/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=1.0328, train_acc=0.6963
[seed 2027] test_loss=1.4652, test_acc=0.5622, lr=1e-05

[seed 2027] Epoch 12/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2027] train_loss=0.8886, train_acc=0.7601
[seed 2027] test_loss=1.5389, test_acc=0.5429, lr=0

  0%|          | 0/2738 [00:00<?, ?it/s]

================================================================================
Starting seed 2028

Loading weights:   0%|          | 0/203 [00:00<?, ?it/s]

ASTForAudioClassification LOAD REPORT from: MIT/ast-finetuned-audioset-10-10-0.4593
Key                     | Status   |
------------------------+----------+---------------------------------------------------------------------------------------
classifier.dense.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([527, 768]) vs model:torch.Size([9, 768])
classifier.dense.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([527]) vs model:torch.Size([9])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

[seed 2028] Epoch 1/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.9568, train_acc=0.2909
[seed 2028] test_loss=1.9344, test_acc=0.2981, lr=0.0001

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 1
[seed 2028] Unfreezing full backbone at epoch 2

[seed 2028] Epoch 2/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.7892, train_acc=0.3774
[seed 2028] test_loss=1.6732, test_acc=0.4256, lr=1e-05

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 2

[seed 2028] Epoch 3/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.5948, train_acc=0.4606
[seed 2028] test_loss=1.5112, test_acc=0.5084, lr=1e-05

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 3

[seed 2028] Epoch 4/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.4732, train_acc=0.5136
[seed 2028] test_loss=1.4369, test_acc=0.5376, lr=9.69846e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 4

[seed 2028] Epoch 5/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.3710, train_acc=0.5582
[seed 2028] test_loss=1.4024, test_acc=0.5570, lr=8.53553e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 5

[seed 2028] Epoch 6/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.2424, train_acc=0.6134
[seed 2028] test_loss=1.3974, test_acc=0.5623, lr=6.1126e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 6

[seed 2028] Epoch 7/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.0898, train_acc=0.6732
[seed 2028] test_loss=1.4219, test_acc=0.5640, lr=2.5e-06

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] Saved new best logits/CSV at epoch 7

[seed 2028] Epoch 8/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.0124, train_acc=0.7079
[seed 2028] test_loss=1.4324, test_acc=0.5618, lr=0

[seed 2028] Epoch 9/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.0739, train_acc=0.6827
[seed 2028] test_loss=1.4323, test_acc=0.5634, lr=5e-06

[seed 2028] Epoch 10/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.0520, train_acc=0.6893
[seed 2028] test_loss=1.4521, test_acc=0.5633, lr=7.5e-06

[seed 2028] Epoch 11/12

  0%|          | 0/2738 [00:00<?, ?it/s]

  0%|          | 0/682 [00:00<?, ?it/s]

[seed 2028] train_loss=1.0324, train_acc=0.7006
[seed 2028] test_loss=1.4697, test_acc=0.5631, lr=1e-05
[seed 2028] Early stopping after 4 epochs without improvement.

  0%|          | 0/2738 [00:00<?, ?it/s]

==== Final Ensemble Results ====
seed=2026 train=0.8013 test=0.5719 best_epoch=10
seed=2027 train=0.7674 test=0.5647 best_epoch=9
seed=2028 train=0.7292 test=0.5640 best_epoch=7
ensemble_test_accuracy=0.5748
Saved ensemble metrics to /content/drive/MyDrive/kaggle_cs3780_sp26/ast_png_spectrogram/ast_png_spectrogram_metrics.json
Saved final ensemble submission to /content/drive/MyDrive/kaggle_cs3780_sp26/ast_png_spectrogram/ast_png_spectrogram_submission.csv

  file_name                     label
0     1.png                Flycatcher
1    10.png                    Parrot
2   100.png  Other non-passerine bird
3  1000.png            Nocturnal bird
4  1001.png              Bird of prey

In [7]:
import copy
import json
import math
import random
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image

from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold
from sklearn.utils.class_weight import compute_class_weight

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from tqdm.auto import tqdm


# =========================================================
# 1. Paths / config
# =========================================================
LOCAL_ROOT = Path("/content/local_data")
LOCAL_DATA_DIR = LOCAL_ROOT / "reduced_64x32"

TRAIN_DIR = LOCAL_DATA_DIR / "train"
TEST_DIR = LOCAL_DATA_DIR / "test"
SOLUTION_CSV = LOCAL_DATA_DIR / "solution.csv"

OUTPUT_DIR = Path("/content/drive/MyDrive/kaggle_cs3780_sp26/cnn_spectrogram_ensemble")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
PIN_MEMORY = torch.cuda.is_available()

print("Using device:", DEVICE)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

SEED = 2026
N_SPLITS = 5
IMG_SIZE = 224

BATCH_SIZE = 64
EPOCHS = 16
PATIENCE = 4
NUM_WORKERS = 4

USE_AMP = True
USE_TTA = True
USE_MIXUP = True
MIXUP_ALPHA = 0.2
EMA_DECAY = 0.999
GRAD_CLIP_NORM = 1.0
LABEL_SMOOTHING = 0.02
WEIGHT_DECAY = 1e-4

# Two-model ensemble
MODEL_SPECS = [
    {
        "name": "convnext_small",
        "lr_head": 3e-4,
        "lr_backbone": 3e-5,
    },
    {
        "name": "efficientnet_v2_s",
        "lr_head": 3e-4,
        "lr_backbone": 3e-5,
    },
]

# head-only warmup, then full finetune
FREEZE_BACKBONE_EPOCHS = 1


# =========================================================
# 2. Utilities
# =========================================================
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)


def save_json(obj, path: Path):
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)


class ModelEMA:
    def __init__(self, model, decay=0.999):
        self.decay = decay
        self.ema = copy.deepcopy(model).eval()
        for p in self.ema.parameters():
            p.requires_grad = False

    @torch.no_grad()
    def update(self, model):
        msd = model.state_dict()
        for k, v in self.ema.state_dict().items():
            src = msd[k].detach()
            if v.dtype.is_floating_point:
                v.copy_(v * self.decay + src * (1.0 - self.decay))
            else:
                v.copy_(src)


def cosine_lr_lambda(current_epoch, total_epochs, warmup_epochs=1):
    if current_epoch < warmup_epochs:
        return float(current_epoch + 1) / float(max(1, warmup_epochs))
    progress = (current_epoch - warmup_epochs) / float(max(1, total_epochs - warmup_epochs))
    return 0.5 * (1.0 + math.cos(math.pi * progress))


def mixup_batch(images, labels, alpha=0.2):
    if alpha <= 0:
        return images, labels, labels, 1.0
    lam = np.random.beta(alpha, alpha)
    idx = torch.randperm(images.size(0), device=images.device)
    mixed = lam * images + (1.0 - lam) * images[idx]
    return mixed, labels, labels[idx], lam


def mixup_loss(criterion, logits, y_a, y_b, lam):
    return lam * criterion(logits, y_a) + (1.0 - lam) * criterion(logits, y_b)


# =========================================================
# 3. Spectrogram transforms
# =========================================================
class SpectrogramTrainTransform:
    def __init__(self, img_size=224):
        self.img_size = img_size
        self.to_tensor = transforms.ToTensor()
        self.normalize = transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225],
        )

    def __call__(self, img: Image.Image):
        # grayscale spectrogram -> repeat to 3 channels
        img = img.convert("L")
        arr = np.array(img).astype(np.uint8)

        # light spectrogram-domain aug
        if random.random() < 0.7:
            shift = random.randint(-3, 3)
            arr = np.roll(arr, shift=shift, axis=1)  # time shift

        if random.random() < 0.25:
            shift = random.randint(-2, 2)
            arr = np.roll(arr, shift=shift, axis=0)  # freq shift

        # time mask
        if random.random() < 0.5:
            w = random.randint(2, max(2, arr.shape[1] // 8))
            x0 = random.randint(0, max(0, arr.shape[1] - w))
            arr[:, x0:x0 + w] = 0

        # freq mask
        if random.random() < 0.5:
            h = random.randint(2, max(2, arr.shape[0] // 6))
            y0 = random.randint(0, max(0, arr.shape[0] - h))
            arr[y0:y0 + h, :] = 0

        img = Image.fromarray(arr, mode="L")
        img = img.resize((self.img_size, self.img_size), resample=Image.BICUBIC)

        # mild brightness/contrast
        if random.random() < 0.4:
            x = np.array(img).astype(np.float32) / 255.0
            scale = random.uniform(0.9, 1.15)
            bias = random.uniform(-0.04, 0.04)
            x = np.clip(x * scale + bias, 0.0, 1.0)
            img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

        img = Image.merge("RGB", (img, img, img))
        x = self.to_tensor(img)
        x = self.normalize(x)
        return x


class SpectrogramEvalTransform:
    def __init__(self, img_size=224):
        self.img_size = img_size
        self.to_tensor = transforms.ToTensor()
        self.normalize = transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225],
        )

    def __call__(self, img: Image.Image):
        img = img.convert("L")
        img = img.resize((self.img_size, self.img_size), resample=Image.BICUBIC)
        img = Image.merge("RGB", (img, img, img))
        x = self.to_tensor(img)
        x = self.normalize(x)
        return x


train_tf = SpectrogramTrainTransform(IMG_SIZE)
eval_tf = SpectrogramEvalTransform(IMG_SIZE)


# =========================================================
# 4. Dataset
# =========================================================
class FullTrainDataset:
    def __init__(self, root_dir: Path):
        self.root_dir = root_dir
        self.classes = sorted([p.name for p in root_dir.iterdir() if p.is_dir()])
        self.class_to_idx = {c: i for i, c in enumerate(self.classes)}
        self.idx_to_class = {i: c for c, i in self.class_to_idx.items()}

        self.samples = []
        for cls_name in self.classes:
            for img_path in sorted((root_dir / cls_name).rglob("*.png")):
                self.samples.append((img_path, self.class_to_idx[cls_name]))

        if not self.samples:
            raise RuntimeError(f"No PNG files found under {root_dir}")

        self.labels = [y for _, y in self.samples]


class TrainValDataset(Dataset):
    def __init__(self, samples, transform):
        self.samples = samples
        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            x = self.transform(img)
        return x, label


class TestDataset(Dataset):
    def __init__(self, test_dir: Path, transform):
        self.image_paths = sorted(test_dir.rglob("*.png"))
        self.transform = transform
        if not self.image_paths:
            raise RuntimeError(f"No PNG files found under {test_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        with Image.open(img_path) as img:
            x = self.transform(img)
        return x, img_path.name


full_train = FullTrainDataset(TRAIN_DIR)
num_classes = len(full_train.classes)

solution_df = pd.read_csv(SOLUTION_CSV)
solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))

print("num_classes =", num_classes)
print("num_train =", len(full_train.samples))


# =========================================================
# 5. Model builders
# =========================================================
def build_model(model_name: str, num_classes: int):
    if model_name == "convnext_small":
        weights = models.ConvNeXt_Small_Weights.DEFAULT
        model = models.convnext_small(weights=weights)
        in_features = model.classifier[2].in_features
        model.classifier[2] = nn.Linear(in_features, num_classes)
        head_modules = [model.classifier]
    elif model_name == "efficientnet_v2_s":
        weights = models.EfficientNet_V2_S_Weights.DEFAULT
        model = models.efficientnet_v2_s(weights=weights)
        in_features = model.classifier[1].in_features
        model.classifier[1] = nn.Linear(in_features, num_classes)
        head_modules = [model.classifier]
    else:
        raise ValueError(model_name)

    return model, head_modules


def freeze_backbone_except_head(model, head_modules):
    for p in model.parameters():
        p.requires_grad = False
    for m in head_modules:
        for p in m.parameters():
            p.requires_grad = True


def unfreeze_all(model):
    for p in model.parameters():
        p.requires_grad = True


def make_optimizer(model, lr):
    return torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=lr,
        weight_decay=WEIGHT_DECAY,
    )


# =========================================================
# 6. Train / eval / predict
# =========================================================
@torch.no_grad()
def eval_epoch(model, loader, criterion, use_tta=False):
    model.eval()
    total_loss = 0.0
    all_logits = []
    all_labels = []
    use_amp = USE_AMP and DEVICE.type == "cuda"

    for x, y in tqdm(loader, leave=False):
        x = x.to(DEVICE, non_blocking=True)
        y = y.to(DEVICE, non_blocking=True)

        if use_tta:
            variants = [
                x,
                torch.roll(x, shifts=4, dims=3),
                torch.roll(x, shifts=-4, dims=3),
                torch.roll(x, shifts=2, dims=2),
                torch.roll(x, shifts=-2, dims=2),
            ]
            logits_sum = 0.0
            for v in variants:
                with torch.autocast(device_type="cuda", enabled=use_amp):
                    logits_sum = logits_sum + model(v)
            logits = logits_sum / len(variants)
        else:
            with torch.autocast(device_type="cuda", enabled=use_amp):
                logits = model(x)

        loss = criterion(logits, y)
        total_loss += loss.item() * x.size(0)
        all_logits.append(logits.float().cpu())
        all_labels.append(y.cpu())

    logits = torch.cat(all_logits).numpy()
    labels = torch.cat(all_labels).numpy()
    preds = logits.argmax(axis=1)
    acc = accuracy_score(labels, preds)
    return total_loss / len(loader.dataset), acc, logits, labels


def train_epoch(model, ema, loader, optimizer, scaler, criterion):
    model.train()
    total_loss = 0.0
    all_preds = []
    all_labels = []
    use_amp = USE_AMP and DEVICE.type == "cuda"

    for x, y in tqdm(loader, leave=False):
        x = x.to(DEVICE, non_blocking=True)
        y = y.to(DEVICE, non_blocking=True)

        if USE_MIXUP:
            x, y_a, y_b, lam = mixup_batch(x, y, MIXUP_ALPHA)

        optimizer.zero_grad(set_to_none=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            logits = model(x)
            if USE_MIXUP:
                loss = mixup_loss(criterion, logits, y_a, y_b, lam)
            else:
                loss = criterion(logits, y)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
        scaler.step(optimizer)
        scaler.update()
        ema.update(model)

        total_loss += loss.item() * x.size(0)
        all_preds.extend(logits.argmax(dim=1).detach().cpu().numpy())
        all_labels.extend(y.detach().cpu().numpy())

    return total_loss / len(loader.dataset), accuracy_score(all_labels, all_preds)


@torch.no_grad()
def predict_logits(model, loader, use_tta=False):
    model.eval()
    all_logits = []
    all_names = []
    use_amp = USE_AMP and DEVICE.type == "cuda"

    for x, names in tqdm(loader, leave=False):
        x = x.to(DEVICE, non_blocking=True)

        if use_tta:
            variants = [
                x,
                torch.roll(x, shifts=4, dims=3),
                torch.roll(x, shifts=-4, dims=3),
                torch.roll(x, shifts=2, dims=2),
                torch.roll(x, shifts=-2, dims=2),
            ]
            logits_sum = 0.0
            for v in variants:
                with torch.autocast(device_type="cuda", enabled=use_amp):
                    logits_sum = logits_sum + model(v)
            logits = logits_sum / len(variants)
        else:
            with torch.autocast(device_type="cuda", enabled=use_amp):
                logits = model(x)

        all_logits.append(logits.float().cpu())
        all_names.extend(list(names))

    return torch.cat(all_logits, dim=0).numpy(), all_names


# =========================================================
# 7. CV training for one model
# =========================================================
def run_model_cv(model_name: str, lr_head: float, lr_backbone: float):
    print("\n" + "=" * 120)
    print(f"Running model: {model_name}")

    model_dir = OUTPUT_DIR / model_name
    model_dir.mkdir(parents=True, exist_ok=True)

    skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)
    oof_logits = np.zeros((len(full_train.samples), num_classes), dtype=np.float32)

    test_dataset = TestDataset(TEST_DIR, eval_tf)
    test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=(NUM_WORKERS > 0),
    )

    test_logits_accum = None
    test_file_order = None
    fold_summaries = []

    class_weights = compute_class_weight(
        class_weight="balanced",
        classes=np.arange(num_classes),
        y=np.array(full_train.labels),
    )
    class_weights = torch.tensor(class_weights, dtype=torch.float32, device=DEVICE)

    for fold, (tr_idx, va_idx) in enumerate(
        skf.split(np.arange(len(full_train.samples)), full_train.labels), start=1
    ):
        print("\n" + "-" * 100)
        print(f"{model_name} | Fold {fold}/{N_SPLITS}")

        fold_dir = model_dir / f"fold_{fold}"
        fold_dir.mkdir(parents=True, exist_ok=True)

        train_samples = [full_train.samples[i] for i in tr_idx]
        val_samples = [full_train.samples[i] for i in va_idx]

        train_ds = TrainValDataset(train_samples, train_tf)
        val_ds = TrainValDataset(val_samples, eval_tf)

        train_loader = DataLoader(
            train_ds,
            batch_size=BATCH_SIZE,
            shuffle=True,
            num_workers=NUM_WORKERS,
            pin_memory=PIN_MEMORY,
            persistent_workers=(NUM_WORKERS > 0),
        )
        val_loader = DataLoader(
            val_ds,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=NUM_WORKERS,
            pin_memory=PIN_MEMORY,
            persistent_workers=(NUM_WORKERS > 0),
        )

        model, head_modules = build_model(model_name, num_classes)
        model = model.to(DEVICE)
        ema = ModelEMA(model, decay=EMA_DECAY)

        criterion = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)

        freeze_backbone_except_head(model, head_modules)
        optimizer = make_optimizer(model, lr_head)
        scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and DEVICE.type == "cuda"))
        scheduler = torch.optim.lr_scheduler.LambdaLR(
            optimizer, lr_lambda=lambda ep: cosine_lr_lambda(ep, EPOCHS, warmup_epochs=1)
        )

        best_val_acc = -1.0
        best_epoch = -1
        best_state = None
        best_val_logits = None
        bad_epochs = 0
        history = []

        for epoch in range(1, EPOCHS + 1):
            if epoch == FREEZE_BACKBONE_EPOCHS + 1:
                print(f"[{model_name}][fold {fold}] unfreezing backbone")
                unfreeze_all(model)
                optimizer = make_optimizer(model, lr_backbone)
                scheduler = torch.optim.lr_scheduler.LambdaLR(
                    optimizer,
                    lr_lambda=lambda ep: cosine_lr_lambda(ep, max(EPOCHS - epoch + 1, 1), warmup_epochs=1)
                )

            print(f"\n[{model_name}][fold {fold}] epoch {epoch}/{EPOCHS}")

            train_loss, train_acc = train_epoch(model, ema, train_loader, optimizer, scaler, criterion)
            val_loss, val_acc, val_logits, val_labels = eval_epoch(
                ema.ema, val_loader, criterion, use_tta=USE_TTA
            )

            history.append({
                "epoch": epoch,
                "train_loss": float(train_loss),
                "train_acc": float(train_acc),
                "val_loss": float(val_loss),
                "val_acc": float(val_acc),
                "lr": float(optimizer.param_groups[0]["lr"]),
            })

            print(
                f"[{model_name}][fold {fold}] "
                f"train_loss={train_loss:.4f} train_acc={train_acc:.4f} "
                f"val_loss={val_loss:.4f} val_acc={val_acc:.4f} "
                f"lr={optimizer.param_groups[0]['lr']:.2e}"
            )

            if val_acc > best_val_acc:
                best_val_acc = val_acc
                best_epoch = epoch
                best_state = copy.deepcopy(ema.ema.state_dict())
                best_val_logits = val_logits.copy()
                bad_epochs = 0
            else:
                bad_epochs += 1

            scheduler.step()

            if bad_epochs >= PATIENCE:
                print(f"[{model_name}][fold {fold}] early stopping")
                break

        ema.ema.load_state_dict(best_state)
        oof_logits[va_idx] = best_val_logits

        fold_test_logits, fold_names = predict_logits(ema.ema, test_loader, use_tta=USE_TTA)
        np.save(fold_dir / "test_logits.npy", fold_test_logits)

        if test_logits_accum is None:
            test_logits_accum = fold_test_logits.astype(np.float64)
            test_file_order = fold_names
        else:
            if test_file_order != fold_names:
                raise RuntimeError("Test file order mismatch across folds.")
            test_logits_accum += fold_test_logits.astype(np.float64)

        fold_summary = {
            "fold": fold,
            "best_val_acc": float(best_val_acc),
            "best_epoch": int(best_epoch),
            "history": history,
        }
        fold_summaries.append(fold_summary)
        save_json(fold_summary, fold_dir / "metrics.json")

    oof_preds = oof_logits.argmax(axis=1)
    oof_acc = accuracy_score(full_train.labels, oof_preds)

    test_logits = test_logits_accum / N_SPLITS
    pred_idx = test_logits.argmax(axis=1)
    pred_labels = [full_train.idx_to_class[int(i)] for i in pred_idx]

    y_true_test = [solution_map[f] for f in test_file_order]
    local_test_acc = float(np.mean(np.array(y_true_test) == np.array(pred_labels)))

    summary = {
        "model_name": model_name,
        "oof_accuracy": float(oof_acc),
        "local_test_accuracy": float(local_test_acc),
        "fold_summaries": fold_summaries,
    }
    save_json(summary, model_dir / "summary.json")

    print(f"\n{model_name} OOF accuracy: {oof_acc:.4f}")
    print(f"{model_name} local test accuracy: {local_test_acc:.4f}")

    return {
        "model_name": model_name,
        "oof_accuracy": float(oof_acc),
        "local_test_accuracy": float(local_test_acc),
        "test_logits": test_logits,
        "test_file_order": test_file_order,
    }


# =========================================================
# 8. Train both models and ensemble
# =========================================================
results = []
for spec in MODEL_SPECS:
    result = run_model_cv(
        model_name=spec["name"],
        lr_head=spec["lr_head"],
        lr_backbone=spec["lr_backbone"],
    )
    results.append(result)

# combine model logits
reference_order = results[0]["test_file_order"]
for r in results[1:]:
    if r["test_file_order"] != reference_order:
        raise RuntimeError("Model-level test file order mismatch.")

ensemble_logits = np.mean(np.stack([r["test_logits"] for r in results], axis=0), axis=0)
ensemble_preds = ensemble_logits.argmax(axis=1)
ensemble_labels = [full_train.idx_to_class[int(i)] for i in ensemble_preds]

submission_df = pd.DataFrame({
    "file_name": reference_order,
    "label": ensemble_labels,
})
submission_path = OUTPUT_DIR / "ensemble_submission.csv"
submission_df.to_csv(submission_path, index=False)

y_true_test = [solution_map[f] for f in reference_order]
ensemble_test_acc = float(np.mean(np.array(y_true_test) == np.array(ensemble_labels)))

summary = {
    "models": [
        {
            "model_name": r["model_name"],
            "oof_accuracy": r["oof_accuracy"],
            "local_test_accuracy": r["local_test_accuracy"],
        }
        for r in results
    ],
    "ensemble_local_test_accuracy": float(ensemble_test_acc),
    "submission_csv": str(submission_path),
}
save_json(summary, OUTPUT_DIR / "ensemble_summary.json")

print("\n" + "=" * 120)
for r in results:
    print(
        f"{r['model_name']}: "
        f"oof={r['oof_accuracy']:.4f} "
        f"local_test={r['local_test_accuracy']:.4f}"
    )
print(f"ensemble_local_test_accuracy={ensemble_test_acc:.4f}")
print(f"Saved submission to: {submission_path}")

submission_df.head()

Using device: cuda
GPU: NVIDIA A100-SXM4-40GB
num_classes = 9
num_train = 21898

========================================================================================================================
Running model: convnext_small

----------------------------------------------------------------------------------------------------
convnext_small | Fold 1/5

[convnext_small][fold 1] epoch 1/16

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=2.0010 train_acc=0.2403 val_loss=2.1497 val_acc=0.2071 lr=3.00e-04
[convnext_small][fold 1] unfreezing backbone

[convnext_small][fold 1] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.9010 train_acc=0.2568 val_loss=2.0186 val_acc=0.2685 lr=3.00e-05

[convnext_small][fold 1] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.7936 train_acc=0.2877 val_loss=1.9042 val_acc=0.3116 lr=3.00e-05

[convnext_small][fold 1] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.7331 train_acc=0.3141 val_loss=1.8020 val_acc=0.3591 lr=2.96e-05

[convnext_small][fold 1] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.6865 train_acc=0.3150 val_loss=1.7079 val_acc=0.3966 lr=2.80e-05

[convnext_small][fold 1] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.6476 train_acc=0.3143 val_loss=1.6285 val_acc=0.4322 lr=2.48e-05

[convnext_small][fold 1] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.6035 train_acc=0.3158 val_loss=1.5672 val_acc=0.4594 lr=1.96e-05

[convnext_small][fold 1] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.5657 train_acc=0.3416 val_loss=1.5214 val_acc=0.4804 lr=1.24e-05

[convnext_small][fold 1] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.5484 train_acc=0.3434 val_loss=1.4885 val_acc=0.4932 lr=4.39e-06

[convnext_small][fold 1] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.5340 train_acc=0.3454 val_loss=1.4667 val_acc=0.5016 lr=0.00e+00

[convnext_small][fold 1] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.5277 train_acc=0.3424 val_loss=1.4515 val_acc=0.5080 lr=7.50e-06

[convnext_small][fold 1] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.5663 train_acc=0.3559 val_loss=1.4403 val_acc=0.5107 lr=2.71e-05

[convnext_small][fold 1] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.5302 train_acc=0.3442 val_loss=1.4296 val_acc=0.5153 lr=1.50e-05

[convnext_small][fold 1] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.5209 train_acc=0.3343 val_loss=1.4202 val_acc=0.5194 lr=2.25e-05

[convnext_small][fold 1] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.5132 train_acc=0.3396 val_loss=1.4106 val_acc=0.5212 lr=3.00e-05

[convnext_small][fold 1] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 1] train_loss=1.4918 train_acc=0.3559 val_loss=1.4073 val_acc=0.5235 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
convnext_small | Fold 2/5

[convnext_small][fold 2] epoch 1/16

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.9998 train_acc=0.2403 val_loss=2.1718 val_acc=0.1406 lr=3.00e-04
[convnext_small][fold 2] unfreezing backbone

[convnext_small][fold 2] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.8823 train_acc=0.2710 val_loss=2.0302 val_acc=0.2804 lr=3.00e-05

[convnext_small][fold 2] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.7877 train_acc=0.2932 val_loss=1.9081 val_acc=0.3384 lr=3.00e-05

[convnext_small][fold 2] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.7327 train_acc=0.2973 val_loss=1.8031 val_acc=0.3799 lr=2.96e-05

[convnext_small][fold 2] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.6699 train_acc=0.3196 val_loss=1.7146 val_acc=0.4078 lr=2.80e-05

[convnext_small][fold 2] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.6327 train_acc=0.3222 val_loss=1.6435 val_acc=0.4272 lr=2.48e-05

[convnext_small][fold 2] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.5983 train_acc=0.3174 val_loss=1.5891 val_acc=0.4409 lr=1.96e-05

[convnext_small][fold 2] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.5620 train_acc=0.3467 val_loss=1.5488 val_acc=0.4521 lr=1.24e-05

[convnext_small][fold 2] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.5490 train_acc=0.3407 val_loss=1.5193 val_acc=0.4696 lr=4.39e-06

[convnext_small][fold 2] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.5300 train_acc=0.3439 val_loss=1.5003 val_acc=0.4799 lr=0.00e+00

[convnext_small][fold 2] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.5332 train_acc=0.3514 val_loss=1.4865 val_acc=0.4849 lr=7.50e-06

[convnext_small][fold 2] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.5706 train_acc=0.3494 val_loss=1.4757 val_acc=0.4897 lr=2.71e-05

[convnext_small][fold 2] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.5265 train_acc=0.3585 val_loss=1.4655 val_acc=0.4916 lr=1.50e-05

[convnext_small][fold 2] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.5061 train_acc=0.3499 val_loss=1.4566 val_acc=0.4968 lr=2.25e-05

[convnext_small][fold 2] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.4989 train_acc=0.3423 val_loss=1.4489 val_acc=0.5023 lr=3.00e-05

[convnext_small][fold 2] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 2] train_loss=1.4906 train_acc=0.3675 val_loss=1.4441 val_acc=0.5027 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
convnext_small | Fold 3/5

[convnext_small][fold 3] epoch 1/16

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=2.0027 train_acc=0.2374 val_loss=2.1686 val_acc=0.1831 lr=3.00e-04
[convnext_small][fold 3] unfreezing backbone

[convnext_small][fold 3] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.8869 train_acc=0.2670 val_loss=2.0166 val_acc=0.2856 lr=3.00e-05

[convnext_small][fold 3] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.7922 train_acc=0.2899 val_loss=1.8921 val_acc=0.3205 lr=3.00e-05

[convnext_small][fold 3] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.7249 train_acc=0.2909 val_loss=1.7915 val_acc=0.3724 lr=2.96e-05

[convnext_small][fold 3] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.6850 train_acc=0.3192 val_loss=1.7093 val_acc=0.4084 lr=2.80e-05

[convnext_small][fold 3] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.6302 train_acc=0.3224 val_loss=1.6394 val_acc=0.4317 lr=2.48e-05

[convnext_small][fold 3] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.5861 train_acc=0.3199 val_loss=1.5813 val_acc=0.4534 lr=1.96e-05

[convnext_small][fold 3] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.5811 train_acc=0.3273 val_loss=1.5366 val_acc=0.4699 lr=1.24e-05

[convnext_small][fold 3] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.5509 train_acc=0.3366 val_loss=1.5053 val_acc=0.4799 lr=4.39e-06

[convnext_small][fold 3] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.5372 train_acc=0.3518 val_loss=1.4849 val_acc=0.4874 lr=0.00e+00

[convnext_small][fold 3] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.5512 train_acc=0.3531 val_loss=1.4697 val_acc=0.4904 lr=7.50e-06

[convnext_small][fold 3] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.5685 train_acc=0.3357 val_loss=1.4570 val_acc=0.4982 lr=2.71e-05

[convnext_small][fold 3] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.5352 train_acc=0.3424 val_loss=1.4456 val_acc=0.5030 lr=1.50e-05

[convnext_small][fold 3] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.5242 train_acc=0.3580 val_loss=1.4342 val_acc=0.5087 lr=2.25e-05

[convnext_small][fold 3] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.5136 train_acc=0.3409 val_loss=1.4234 val_acc=0.5146 lr=3.00e-05

[convnext_small][fold 3] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 3] train_loss=1.4867 train_acc=0.3530 val_loss=1.4158 val_acc=0.5171 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
convnext_small | Fold 4/5

[convnext_small][fold 4] epoch 1/16

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=2.0055 train_acc=0.2353 val_loss=2.1540 val_acc=0.2076 lr=3.00e-04
[convnext_small][fold 4] unfreezing backbone

[convnext_small][fold 4] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.8871 train_acc=0.2612 val_loss=2.0139 val_acc=0.2827 lr=3.00e-05

[convnext_small][fold 4] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.7866 train_acc=0.2864 val_loss=1.8994 val_acc=0.3238 lr=3.00e-05

[convnext_small][fold 4] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.7215 train_acc=0.3049 val_loss=1.8026 val_acc=0.3679 lr=2.96e-05

[convnext_small][fold 4] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.6791 train_acc=0.3171 val_loss=1.7180 val_acc=0.3996 lr=2.80e-05

[convnext_small][fold 4] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.6435 train_acc=0.3121 val_loss=1.6478 val_acc=0.4266 lr=2.48e-05

[convnext_small][fold 4] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.6183 train_acc=0.3345 val_loss=1.5927 val_acc=0.4487 lr=1.96e-05

[convnext_small][fold 4] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.5801 train_acc=0.3252 val_loss=1.5504 val_acc=0.4617 lr=1.24e-05

[convnext_small][fold 4] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.5520 train_acc=0.3372 val_loss=1.5201 val_acc=0.4759 lr=4.39e-06

[convnext_small][fold 4] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.5302 train_acc=0.3297 val_loss=1.4996 val_acc=0.4800 lr=0.00e+00

[convnext_small][fold 4] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.5383 train_acc=0.3600 val_loss=1.4861 val_acc=0.4887 lr=7.50e-06

[convnext_small][fold 4] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.5583 train_acc=0.3455 val_loss=1.4741 val_acc=0.4933 lr=2.71e-05

[convnext_small][fold 4] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.5223 train_acc=0.3473 val_loss=1.4639 val_acc=0.5001 lr=1.50e-05

[convnext_small][fold 4] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.5121 train_acc=0.3640 val_loss=1.4545 val_acc=0.5063 lr=2.25e-05

[convnext_small][fold 4] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.5290 train_acc=0.3471 val_loss=1.4447 val_acc=0.5090 lr=3.00e-05

[convnext_small][fold 4] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 4] train_loss=1.4870 train_acc=0.3459 val_loss=1.4376 val_acc=0.5111 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
convnext_small | Fold 5/5

[convnext_small][fold 5] epoch 1/16

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=2.0011 train_acc=0.2369 val_loss=2.1550 val_acc=0.1587 lr=3.00e-04
[convnext_small][fold 5] unfreezing backbone

[convnext_small][fold 5] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.8797 train_acc=0.2545 val_loss=2.0068 val_acc=0.2930 lr=3.00e-05

[convnext_small][fold 5] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.7876 train_acc=0.2848 val_loss=1.8845 val_acc=0.3348 lr=3.00e-05

[convnext_small][fold 5] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.7280 train_acc=0.3016 val_loss=1.7854 val_acc=0.3715 lr=2.96e-05

[convnext_small][fold 5] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.6822 train_acc=0.3110 val_loss=1.7015 val_acc=0.4015 lr=2.80e-05

[convnext_small][fold 5] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.6313 train_acc=0.3230 val_loss=1.6314 val_acc=0.4286 lr=2.48e-05

[convnext_small][fold 5] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.6094 train_acc=0.3276 val_loss=1.5743 val_acc=0.4506 lr=1.96e-05

[convnext_small][fold 5] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.5933 train_acc=0.3363 val_loss=1.5311 val_acc=0.4659 lr=1.24e-05

[convnext_small][fold 5] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.5798 train_acc=0.3447 val_loss=1.4992 val_acc=0.4782 lr=4.39e-06

[convnext_small][fold 5] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.5346 train_acc=0.3545 val_loss=1.4777 val_acc=0.4892 lr=0.00e+00

[convnext_small][fold 5] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.5471 train_acc=0.3488 val_loss=1.4618 val_acc=0.4976 lr=7.50e-06

[convnext_small][fold 5] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.5535 train_acc=0.3284 val_loss=1.4495 val_acc=0.5051 lr=2.71e-05

[convnext_small][fold 5] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.5243 train_acc=0.3549 val_loss=1.4368 val_acc=0.5079 lr=1.50e-05

[convnext_small][fold 5] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.5209 train_acc=0.3406 val_loss=1.4262 val_acc=0.5127 lr=2.25e-05

[convnext_small][fold 5] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.5134 train_acc=0.3350 val_loss=1.4160 val_acc=0.5166 lr=3.00e-05

[convnext_small][fold 5] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[convnext_small][fold 5] train_loss=1.4948 train_acc=0.3611 val_loss=1.4088 val_acc=0.5175 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

convnext_small OOF accuracy: 0.5144
convnext_small local test accuracy: 0.5281

========================================================================================================================
Running model: efficientnet_v2_s

----------------------------------------------------------------------------------------------------
efficientnet_v2_s | Fold 1/5
Downloading: "https://download.pytorch.org/models/efficientnet_v2_s-dd5fe13b.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_v2_s-dd5fe13b.pth

100%|██████████| 82.7M/82.7M [00:00<00:00, 208MB/s]

[efficientnet_v2_s][fold 1] epoch 1/16

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=2.0487 train_acc=0.2298 val_loss=2.1772 val_acc=0.1639 lr=3.00e-04
[efficientnet_v2_s][fold 1] unfreezing backbone

[efficientnet_v2_s][fold 1] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.9501 train_acc=0.2444 val_loss=2.1529 val_acc=0.2096 lr=3.00e-05

[efficientnet_v2_s][fold 1] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.8973 train_acc=0.2602 val_loss=2.1171 val_acc=0.2429 lr=3.00e-05

[efficientnet_v2_s][fold 1] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.8474 train_acc=0.2666 val_loss=2.0629 val_acc=0.2619 lr=2.96e-05

[efficientnet_v2_s][fold 1] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.8118 train_acc=0.2833 val_loss=1.9982 val_acc=0.2900 lr=2.80e-05

[efficientnet_v2_s][fold 1] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.7755 train_acc=0.2830 val_loss=1.9362 val_acc=0.3119 lr=2.48e-05

[efficientnet_v2_s][fold 1] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.7273 train_acc=0.2890 val_loss=1.8749 val_acc=0.3377 lr=1.96e-05

[efficientnet_v2_s][fold 1] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.7144 train_acc=0.2962 val_loss=1.8204 val_acc=0.3562 lr=1.24e-05

[efficientnet_v2_s][fold 1] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.6923 train_acc=0.3042 val_loss=1.7740 val_acc=0.3756 lr=4.39e-06

[efficientnet_v2_s][fold 1] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.6830 train_acc=0.3060 val_loss=1.7371 val_acc=0.3897 lr=0.00e+00

[efficientnet_v2_s][fold 1] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.6820 train_acc=0.2952 val_loss=1.7084 val_acc=0.4016 lr=7.50e-06

[efficientnet_v2_s][fold 1] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.6759 train_acc=0.3028 val_loss=1.6824 val_acc=0.4123 lr=2.71e-05

[efficientnet_v2_s][fold 1] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.6525 train_acc=0.3161 val_loss=1.6565 val_acc=0.4251 lr=1.50e-05

[efficientnet_v2_s][fold 1] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.6176 train_acc=0.3160 val_loss=1.6325 val_acc=0.4336 lr=2.25e-05

[efficientnet_v2_s][fold 1] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.6296 train_acc=0.3294 val_loss=1.6086 val_acc=0.4427 lr=3.00e-05

[efficientnet_v2_s][fold 1] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 1] train_loss=1.6006 train_acc=0.3233 val_loss=1.5868 val_acc=0.4507 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
efficientnet_v2_s | Fold 2/5

[efficientnet_v2_s][fold 2] epoch 1/16

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=2.0479 train_acc=0.2307 val_loss=2.1852 val_acc=0.1888 lr=3.00e-04
[efficientnet_v2_s][fold 2] unfreezing backbone

[efficientnet_v2_s][fold 2] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.9498 train_acc=0.2521 val_loss=2.1610 val_acc=0.2096 lr=3.00e-05

[efficientnet_v2_s][fold 2] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.8880 train_acc=0.2635 val_loss=2.1318 val_acc=0.2210 lr=3.00e-05

[efficientnet_v2_s][fold 2] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.8447 train_acc=0.2741 val_loss=2.0776 val_acc=0.2537 lr=2.96e-05

[efficientnet_v2_s][fold 2] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.8025 train_acc=0.2762 val_loss=2.0109 val_acc=0.2833 lr=2.80e-05

[efficientnet_v2_s][fold 2] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.7505 train_acc=0.2979 val_loss=1.9440 val_acc=0.3073 lr=2.48e-05

[efficientnet_v2_s][fold 2] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.7040 train_acc=0.3121 val_loss=1.8860 val_acc=0.3247 lr=1.96e-05

[efficientnet_v2_s][fold 2] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.7016 train_acc=0.3062 val_loss=1.8354 val_acc=0.3461 lr=1.24e-05

[efficientnet_v2_s][fold 2] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.6547 train_acc=0.3163 val_loss=1.7908 val_acc=0.3669 lr=4.39e-06

[efficientnet_v2_s][fold 2] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.6641 train_acc=0.3317 val_loss=1.7542 val_acc=0.3813 lr=0.00e+00

[efficientnet_v2_s][fold 2] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.6586 train_acc=0.3097 val_loss=1.7242 val_acc=0.3895 lr=7.50e-06

[efficientnet_v2_s][fold 2] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.6535 train_acc=0.3111 val_loss=1.6971 val_acc=0.4000 lr=2.71e-05

[efficientnet_v2_s][fold 2] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.6236 train_acc=0.3221 val_loss=1.6726 val_acc=0.4084 lr=1.50e-05

[efficientnet_v2_s][fold 2] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.5924 train_acc=0.3200 val_loss=1.6471 val_acc=0.4228 lr=2.25e-05

[efficientnet_v2_s][fold 2] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.5772 train_acc=0.3348 val_loss=1.6224 val_acc=0.4258 lr=3.00e-05

[efficientnet_v2_s][fold 2] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 2] train_loss=1.5513 train_acc=0.3470 val_loss=1.6036 val_acc=0.4358 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
efficientnet_v2_s | Fold 3/5

[efficientnet_v2_s][fold 3] epoch 1/16

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=2.0511 train_acc=0.2261 val_loss=2.1862 val_acc=0.1562 lr=3.00e-04
[efficientnet_v2_s][fold 3] unfreezing backbone

[efficientnet_v2_s][fold 3] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.9553 train_acc=0.2458 val_loss=2.1469 val_acc=0.2071 lr=3.00e-05

[efficientnet_v2_s][fold 3] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.8884 train_acc=0.2604 val_loss=2.1052 val_acc=0.2292 lr=3.00e-05

[efficientnet_v2_s][fold 3] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.8359 train_acc=0.2754 val_loss=2.0535 val_acc=0.2562 lr=2.96e-05

[efficientnet_v2_s][fold 3] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.7960 train_acc=0.2850 val_loss=1.9966 val_acc=0.2788 lr=2.80e-05

[efficientnet_v2_s][fold 3] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.7489 train_acc=0.2889 val_loss=1.9415 val_acc=0.3046 lr=2.48e-05

[efficientnet_v2_s][fold 3] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.7099 train_acc=0.3009 val_loss=1.8886 val_acc=0.3279 lr=1.96e-05

[efficientnet_v2_s][fold 3] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.6872 train_acc=0.3041 val_loss=1.8399 val_acc=0.3521 lr=1.24e-05

[efficientnet_v2_s][fold 3] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.6753 train_acc=0.3056 val_loss=1.7969 val_acc=0.3705 lr=4.39e-06

[efficientnet_v2_s][fold 3] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.6597 train_acc=0.3101 val_loss=1.7620 val_acc=0.3895 lr=0.00e+00

[efficientnet_v2_s][fold 3] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.6644 train_acc=0.3310 val_loss=1.7332 val_acc=0.3973 lr=7.50e-06

[efficientnet_v2_s][fold 3] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.6573 train_acc=0.3138 val_loss=1.7049 val_acc=0.4041 lr=2.71e-05

[efficientnet_v2_s][fold 3] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.6349 train_acc=0.3087 val_loss=1.6773 val_acc=0.4155 lr=1.50e-05

[efficientnet_v2_s][fold 3] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.6061 train_acc=0.3240 val_loss=1.6518 val_acc=0.4267 lr=2.25e-05

[efficientnet_v2_s][fold 3] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.6046 train_acc=0.3303 val_loss=1.6261 val_acc=0.4347 lr=3.00e-05

[efficientnet_v2_s][fold 3] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 3] train_loss=1.5739 train_acc=0.3315 val_loss=1.6027 val_acc=0.4422 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
efficientnet_v2_s | Fold 4/5

[efficientnet_v2_s][fold 4] epoch 1/16

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=2.0515 train_acc=0.2331 val_loss=2.1653 val_acc=0.1644 lr=3.00e-04
[efficientnet_v2_s][fold 4] unfreezing backbone

[efficientnet_v2_s][fold 4] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.9551 train_acc=0.2466 val_loss=2.1428 val_acc=0.1898 lr=3.00e-05

[efficientnet_v2_s][fold 4] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.8912 train_acc=0.2587 val_loss=2.1119 val_acc=0.2290 lr=3.00e-05

[efficientnet_v2_s][fold 4] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.8470 train_acc=0.2715 val_loss=2.0592 val_acc=0.2590 lr=2.96e-05

[efficientnet_v2_s][fold 4] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.8060 train_acc=0.2752 val_loss=1.9918 val_acc=0.2852 lr=2.80e-05

[efficientnet_v2_s][fold 4] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.7478 train_acc=0.2977 val_loss=1.9294 val_acc=0.3055 lr=2.48e-05

[efficientnet_v2_s][fold 4] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.7279 train_acc=0.2943 val_loss=1.8752 val_acc=0.3284 lr=1.96e-05

[efficientnet_v2_s][fold 4] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.6829 train_acc=0.3181 val_loss=1.8271 val_acc=0.3451 lr=1.24e-05

[efficientnet_v2_s][fold 4] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.6822 train_acc=0.2980 val_loss=1.7863 val_acc=0.3649 lr=4.39e-06

[efficientnet_v2_s][fold 4] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.6648 train_acc=0.3179 val_loss=1.7538 val_acc=0.3784 lr=0.00e+00

[efficientnet_v2_s][fold 4] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.6703 train_acc=0.3114 val_loss=1.7276 val_acc=0.3903 lr=7.50e-06

[efficientnet_v2_s][fold 4] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.6738 train_acc=0.3035 val_loss=1.7028 val_acc=0.4012 lr=2.71e-05

[efficientnet_v2_s][fold 4] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.6486 train_acc=0.3219 val_loss=1.6798 val_acc=0.4060 lr=1.50e-05

[efficientnet_v2_s][fold 4] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.6074 train_acc=0.3178 val_loss=1.6574 val_acc=0.4209 lr=2.25e-05

[efficientnet_v2_s][fold 4] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.6060 train_acc=0.3214 val_loss=1.6391 val_acc=0.4254 lr=3.00e-05

[efficientnet_v2_s][fold 4] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 4] train_loss=1.5521 train_acc=0.3210 val_loss=1.6216 val_acc=0.4337 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
efficientnet_v2_s | Fold 5/5

[efficientnet_v2_s][fold 5] epoch 1/16

  0%|          | 0/274 [00:00<?, ?it/s]

/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")
/tmp/ipykernel_2308/1362803534.py:172: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray(arr, mode="L")
/tmp/ipykernel_2308/1362803534.py:181: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  img = Image.fromarray((x * 255).astype(np.uint8), mode="L")

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=2.0491 train_acc=0.2295 val_loss=2.1716 val_acc=0.2053 lr=3.00e-04
[efficientnet_v2_s][fold 5] unfreezing backbone

[efficientnet_v2_s][fold 5] epoch 2/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.9509 train_acc=0.2493 val_loss=2.1428 val_acc=0.2167 lr=3.00e-05

[efficientnet_v2_s][fold 5] epoch 3/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.8916 train_acc=0.2585 val_loss=2.1052 val_acc=0.2327 lr=3.00e-05

[efficientnet_v2_s][fold 5] epoch 4/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.8573 train_acc=0.2762 val_loss=2.0509 val_acc=0.2587 lr=2.96e-05

[efficientnet_v2_s][fold 5] epoch 5/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.8123 train_acc=0.2813 val_loss=1.9882 val_acc=0.2820 lr=2.80e-05

[efficientnet_v2_s][fold 5] epoch 6/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.7745 train_acc=0.2888 val_loss=1.9253 val_acc=0.3037 lr=2.48e-05

[efficientnet_v2_s][fold 5] epoch 7/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.7326 train_acc=0.2941 val_loss=1.8667 val_acc=0.3343 lr=1.96e-05

[efficientnet_v2_s][fold 5] epoch 8/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.7062 train_acc=0.3089 val_loss=1.8154 val_acc=0.3581 lr=1.24e-05

[efficientnet_v2_s][fold 5] epoch 9/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.6852 train_acc=0.3207 val_loss=1.7722 val_acc=0.3763 lr=4.39e-06

[efficientnet_v2_s][fold 5] epoch 10/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.6814 train_acc=0.3111 val_loss=1.7369 val_acc=0.3926 lr=0.00e+00

[efficientnet_v2_s][fold 5] epoch 11/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.6879 train_acc=0.3185 val_loss=1.7087 val_acc=0.4024 lr=7.50e-06

[efficientnet_v2_s][fold 5] epoch 12/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.6596 train_acc=0.3073 val_loss=1.6817 val_acc=0.4129 lr=2.71e-05

[efficientnet_v2_s][fold 5] epoch 13/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.6379 train_acc=0.3260 val_loss=1.6555 val_acc=0.4266 lr=1.50e-05

[efficientnet_v2_s][fold 5] epoch 14/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.6213 train_acc=0.3132 val_loss=1.6304 val_acc=0.4341 lr=2.25e-05

[efficientnet_v2_s][fold 5] epoch 15/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.6001 train_acc=0.3242 val_loss=1.6046 val_acc=0.4451 lr=3.00e-05

[efficientnet_v2_s][fold 5] epoch 16/16

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/69 [00:00<?, ?it/s]

[efficientnet_v2_s][fold 5] train_loss=1.5785 train_acc=0.3401 val_loss=1.5847 val_acc=0.4492 lr=0.00e+00

  0%|          | 0/86 [00:00<?, ?it/s]

efficientnet_v2_s OOF accuracy: 0.4423
efficientnet_v2_s local test accuracy: 0.4523

========================================================================================================================
convnext_small: oof=0.5144 local_test=0.5281
efficientnet_v2_s: oof=0.4423 local_test=0.4523
ensemble_local_test_accuracy=0.5128
Saved submission to: /content/drive/MyDrive/kaggle_cs3780_sp26/cnn_spectrogram_ensemble/ensemble_submission.csv

  file_name                  label
0     1.png         Nocturnal bird
1    10.png  Water-associated bird
2   100.png             Flycatcher
3  1000.png         Nocturnal bird
4  1001.png             Flycatcher