In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import torch
print(torch.cuda.is_available())

True

In [ ]:
#!/usr/bin/env python3

import argparse
import json
import random
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image
from sklearn.metrics import accuracy_score, classification_report
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from tqdm import tqdm

from pathlib import Path

BASE_DATA_ROOT = Path("drive/MyDrive/kaggle_cs3780_sp26/lowdim_export")
TRAIN_SUBDIR = Path("reduced_64x32/train")
TEST_SUBDIR = Path("reduced_64x32/test")
SOLUTION_CSV = Path("drive/MyDrive/kaggle_cs3780_sp26/lowdim_export/reduced_64x32/solution.csv")
OUTPUT = Path("drive/MyDrive/kaggle_cs3780_sp26/gpu_models_metrics.json")

IMG_HEIGHT = 32
IMG_WIDTH = 64
BATCH_SIZE = 256
EPOCHS = 20
LR_LOGREG = 1e-2
LR_CNN = 1e-3
NUM_WORKERS = 2
SEED = 2026


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


class TrainFolderDataset(Dataset):
    def __init__(self, root_dir: Path, transform=None):
        self.root_dir = root_dir
        self.transform = transform

        self.classes = sorted([p.name for p in root_dir.iterdir() if p.is_dir()])
        if not self.classes:
            raise FileNotFoundError(f"No class folders found under {root_dir}")

        self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}
        self.samples = []

        for cls_name in self.classes:
            class_dir = root_dir / cls_name
            for img_path in sorted(class_dir.rglob("*.png")):
                self.samples.append((img_path, self.class_to_idx[cls_name]))

        if not self.samples:
            raise FileNotFoundError(f"No PNG files found under {root_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("L")
            if self.transform is not None:
                img = self.transform(img)
        return img, label


class TestWithSolutionDataset(Dataset):
    def __init__(self, test_dir: Path, solution_csv: Path, class_to_idx: dict[str, int], transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.class_to_idx = class_to_idx

        solution_df = pd.read_csv(solution_csv)
        if "file_name" not in solution_df.columns or "label" not in solution_df.columns:
            raise ValueError("solution.csv must contain columns: file_name, label")

        solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))

        self.samples = []
        image_paths = sorted(test_dir.rglob("*.png"))
        if not image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

        for img_path in image_paths:
            fname = img_path.name
            if fname not in solution_map:
                raise KeyError(f"{fname} not found in solution.csv")
            label_name = solution_map[fname]
            if label_name not in class_to_idx:
                raise KeyError(f"Label {label_name} from solution.csv not found in training classes")
            label_idx = class_to_idx[label_name]
            self.samples.append((img_path, label_idx))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("L")
            if self.transform is not None:
                img = self.transform(img)
        return img, label


class LogisticRegressionTorch(nn.Module):
    def __init__(self, input_dim: int, num_classes: int):
        super().__init__()
        self.linear = nn.Linear(input_dim, num_classes)

    def forward(self, x):
        x = x.view(x.size(0), -1)
        return self.linear(x)


class SmallBirdCNN(nn.Module):
    def __init__(self, num_classes: int):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),   # 32x64 -> 16x32

            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),   # 16x32 -> 8x16

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),   # 8x16 -> 4x8
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 4 * 8, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes),
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x


def run_one_epoch(model, loader, criterion, optimizer, device, train: bool):
    if train:
        model.train()
    else:
        model.eval()

    total_loss = 0.0
    all_preds = []
    all_labels = []

    context = torch.enable_grad() if train else torch.no_grad()
    with context:
        for images, labels in tqdm(loader, leave=False):
            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            if train:
                optimizer.zero_grad()

            logits = model(images)
            loss = criterion(logits, labels)

            if train:
                loss.backward()
                optimizer.step()

            total_loss += loss.item() * images.size(0)
            preds = logits.argmax(dim=1)

            all_preds.extend(preds.detach().cpu().numpy())
            all_labels.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc, np.array(all_labels), np.array(all_preds)


def train_model(model, model_name, train_loader, test_loader, classes, device, epochs, lr):
    model = model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    history = []
    best_test_acc = -1.0
    best_y_true = None
    best_y_pred = None

    for epoch in range(1, epochs + 1):
        print(f"\n[{model_name}] Epoch {epoch}/{epochs}")
        train_loss, train_acc, _, _ = run_one_epoch(model, train_loader, criterion, optimizer, device, train=True)
        test_loss, test_acc, y_true, y_pred = run_one_epoch(model, test_loader, criterion, optimizer, device, train=False)

        print(f"[{model_name}] train_loss={train_loss:.4f}, train_acc={train_acc:.4f}")
        print(f"[{model_name}] test_loss={test_loss:.4f}, test_acc={test_acc:.4f}")

        history.append({
            "epoch": epoch,
            "train_loss": float(train_loss),
            "train_accuracy": float(train_acc),
            "test_loss": float(test_loss),
            "test_accuracy": float(test_acc),
        })

        if test_acc > best_test_acc:
            best_test_acc = test_acc
            best_y_true = y_true
            best_y_pred = y_pred

    report = classification_report(
        best_y_true,
        best_y_pred,
        target_names=classes,
        output_dict=True,
        zero_division=0,
    )

    final_train_loss, final_train_acc, _, _ = run_one_epoch(model, train_loader, criterion, optimizer, device, train=False)

    return {
        "final_train_accuracy": float(final_train_acc),
        "best_test_accuracy": float(best_test_acc),
        "history": history,
        "classification_report": report,
    }


def main():
    set_seed(SEED)

    train_dir = BASE_DATA_ROOT / TRAIN_SUBDIR
    test_dir = BASE_DATA_ROOT / TEST_SUBDIR
    solution_csv = SOLUTION_CSV

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")

    transform = transforms.Compose([
        transforms.Resize((IMG_HEIGHT, IMG_WIDTH)),
        transforms.ToTensor(),
    ])

    train_dataset = TrainFolderDataset(train_dir, transform=transform)
    test_dataset = TestWithSolutionDataset(
        test_dir=test_dir,
        solution_csv=solution_csv,
        class_to_idx=train_dataset.class_to_idx,
        transform=transform,
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=True,
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=True,
    )

    num_classes = len(train_dataset.classes)
    input_dim = IMG_HEIGHT * IMG_WIDTH

    logreg_model = LogisticRegressionTorch(input_dim=input_dim, num_classes=num_classes)
    cnn_model = SmallBirdCNN(num_classes=num_classes)

    logreg_results = train_model(
        model=logreg_model,
        model_name="gpu_logistic_regression",
        train_loader=train_loader,
        test_loader=test_loader,
        classes=train_dataset.classes,
        device=device,
        epochs=EPOCHS,
        lr=LR_LOGREG,
    )

    cnn_results = train_model(
        model=cnn_model,
        model_name="gpu_cnn",
        train_loader=train_loader,
        test_loader=test_loader,
        classes=train_dataset.classes,
        device=device,
        epochs=EPOCHS,
        lr=LR_CNN,
    )

    results = {
        "config": {
            "train_dir": str(train_dir),
            "test_dir": str(test_dir),
            "solution_csv": str(solution_csv),
            "img_height": IMG_HEIGHT,
            "img_width": IMG_WIDTH,
            "batch_size": BATCH_SIZE,
            "epochs": EPOCHS,
            "lr_logreg": LR_LOGREG,
            "lr_cnn": LR_CNN,
            "seed": SEED,
            "device": str(device),
        },
        "num_train": len(train_dataset),
        "num_test": len(test_dataset),
        "num_classes": num_classes,
        "classes": train_dataset.classes,
        "models": {
            "gpu_logistic_regression": logreg_results,
            "gpu_cnn": cnn_results,
        },
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    print("\n==== Final Results ====")
    print(
        f"gpu_logistic_regression train={logreg_results['final_train_accuracy']:.4f}, "
        f"test={logreg_results['best_test_accuracy']:.4f}"
    )
    print(
        f"gpu_cnn train={cnn_results['final_train_accuracy']:.4f}, "
        f"test={cnn_results['best_test_accuracy']:.4f}"
    )
    print(f"Saved metrics to {OUTPUT}")


if __name__ == "__main__":
    main()

Using device: cuda
GPU: Tesla T4

[gpu_logistic_regression] Epoch 1/20

[gpu_logistic_regression] train_loss=3.6469, train_acc=0.1786
[gpu_logistic_regression] test_loss=2.6479, test_acc=0.1786

[gpu_logistic_regression] Epoch 2/20

[gpu_logistic_regression] train_loss=2.1240, train_acc=0.2309
[gpu_logistic_regression] test_loss=3.1303, test_acc=0.1701

[gpu_logistic_regression] Epoch 3/20

[gpu_logistic_regression] train_loss=2.1593, train_acc=0.2365
[gpu_logistic_regression] test_loss=5.0807, test_acc=0.0659

[gpu_logistic_regression] Epoch 4/20

[gpu_logistic_regression] train_loss=2.2784, train_acc=0.2333
[gpu_logistic_regression] test_loss=3.4914, test_acc=0.0695

[gpu_logistic_regression] Epoch 5/20

[gpu_logistic_regression] train_loss=2.0984, train_acc=0.2544
[gpu_logistic_regression] test_loss=3.4159, test_acc=0.0973

[gpu_logistic_regression] Epoch 6/20

[gpu_logistic_regression] train_loss=2.1569, train_acc=0.2498
[gpu_logistic_regression] test_loss=3.6850, test_acc=0.1078

[gpu_logistic_regression] Epoch 7/20

[gpu_logistic_regression] train_loss=2.1899, train_acc=0.2480
[gpu_logistic_regression] test_loss=2.5822, test_acc=0.1320

[gpu_logistic_regression] Epoch 8/20

[gpu_logistic_regression] train_loss=2.0897, train_acc=0.2580
[gpu_logistic_regression] test_loss=2.9306, test_acc=0.2167

[gpu_logistic_regression] Epoch 9/20

[gpu_logistic_regression] train_loss=2.1879, train_acc=0.2477
[gpu_logistic_regression] test_loss=2.7534, test_acc=0.1740

[gpu_logistic_regression] Epoch 10/20

[gpu_logistic_regression] train_loss=2.1033, train_acc=0.2557
[gpu_logistic_regression] test_loss=7.5823, test_acc=0.0487

[gpu_logistic_regression] Epoch 11/20

[gpu_logistic_regression] train_loss=2.3394, train_acc=0.2516
[gpu_logistic_regression] test_loss=3.9947, test_acc=0.1480

[gpu_logistic_regression] Epoch 12/20

[gpu_logistic_regression] train_loss=2.3362, train_acc=0.2476
[gpu_logistic_regression] test_loss=2.6981, test_acc=0.1872

[gpu_logistic_regression] Epoch 13/20

[gpu_logistic_regression] train_loss=2.0975, train_acc=0.2610
[gpu_logistic_regression] test_loss=2.9106, test_acc=0.2203

[gpu_logistic_regression] Epoch 14/20

[gpu_logistic_regression] train_loss=2.0746, train_acc=0.2711
[gpu_logistic_regression] test_loss=3.3929, test_acc=0.1055

[gpu_logistic_regression] Epoch 15/20

[gpu_logistic_regression] train_loss=2.1728, train_acc=0.2639
[gpu_logistic_regression] test_loss=3.1109, test_acc=0.1132

[gpu_logistic_regression] Epoch 16/20

[gpu_logistic_regression] train_loss=2.1145, train_acc=0.2645
[gpu_logistic_regression] test_loss=2.8297, test_acc=0.2184

[gpu_logistic_regression] Epoch 17/20

[gpu_logistic_regression] train_loss=2.0628, train_acc=0.2723
[gpu_logistic_regression] test_loss=5.1160, test_acc=0.0731

[gpu_logistic_regression] Epoch 18/20

[gpu_logistic_regression] train_loss=2.3483, train_acc=0.2597
[gpu_logistic_regression] test_loss=3.7635, test_acc=0.1368

[gpu_logistic_regression] Epoch 19/20

[gpu_logistic_regression] train_loss=2.1830, train_acc=0.2664
[gpu_logistic_regression] test_loss=8.7607, test_acc=0.0654

[gpu_logistic_regression] Epoch 20/20

[gpu_logistic_regression] train_loss=2.6491, train_acc=0.2782
[gpu_logistic_regression] test_loss=3.1081, test_acc=0.0932

[gpu_cnn] Epoch 1/20

[gpu_cnn] train_loss=2.1400, train_acc=0.2111
[gpu_cnn] test_loss=2.0960, test_acc=0.2368

[gpu_cnn] Epoch 2/20

[gpu_cnn] train_loss=2.0673, train_acc=0.2425
[gpu_cnn] test_loss=2.0428, test_acc=0.2671

[gpu_cnn] Epoch 3/20

[gpu_cnn] train_loss=1.9968, train_acc=0.2631
[gpu_cnn] test_loss=1.9967, test_acc=0.2718

[gpu_cnn] Epoch 4/20

[gpu_cnn] train_loss=1.9499, train_acc=0.2861
[gpu_cnn] test_loss=1.9176, test_acc=0.2941

[gpu_cnn] Epoch 5/20

[gpu_cnn] train_loss=1.8916, train_acc=0.3108
[gpu_cnn] test_loss=1.8676, test_acc=0.3122

[gpu_cnn] Epoch 6/20

[gpu_cnn] train_loss=1.8609, train_acc=0.3235
[gpu_cnn] test_loss=1.8340, test_acc=0.3422

[gpu_cnn] Epoch 7/20

[gpu_cnn] train_loss=1.8350, train_acc=0.3365
[gpu_cnn] test_loss=1.8007, test_acc=0.3537

[gpu_cnn] Epoch 8/20

[gpu_cnn] train_loss=1.8133, train_acc=0.3500
[gpu_cnn] test_loss=1.8108, test_acc=0.3612

[gpu_cnn] Epoch 9/20

[gpu_cnn] train_loss=1.8144, train_acc=0.3473
[gpu_cnn] test_loss=1.7699, test_acc=0.3733

[gpu_cnn] Epoch 10/20

[gpu_cnn] train_loss=1.7852, train_acc=0.3584
[gpu_cnn] test_loss=1.7488, test_acc=0.3769

[gpu_cnn] Epoch 11/20

[gpu_cnn] train_loss=1.7654, train_acc=0.3641
[gpu_cnn] test_loss=1.7305, test_acc=0.3838

[gpu_cnn] Epoch 12/20

[gpu_cnn] train_loss=1.7467, train_acc=0.3751
[gpu_cnn] test_loss=1.7279, test_acc=0.3825

[gpu_cnn] Epoch 13/20

[gpu_cnn] train_loss=1.7326, train_acc=0.3772
[gpu_cnn] test_loss=1.7092, test_acc=0.3856

[gpu_cnn] Epoch 14/20

[gpu_cnn] train_loss=1.7193, train_acc=0.3819
[gpu_cnn] test_loss=1.7131, test_acc=0.3912

[gpu_cnn] Epoch 15/20

[gpu_cnn] train_loss=1.7166, train_acc=0.3831
[gpu_cnn] test_loss=1.7338, test_acc=0.3878

[gpu_cnn] Epoch 16/20

[gpu_cnn] train_loss=1.7187, train_acc=0.3862
[gpu_cnn] test_loss=1.6869, test_acc=0.3984

[gpu_cnn] Epoch 17/20

[gpu_cnn] train_loss=1.6902, train_acc=0.3901
[gpu_cnn] test_loss=1.6859, test_acc=0.4029

[gpu_cnn] Epoch 18/20

[gpu_cnn] train_loss=1.6777, train_acc=0.4000
[gpu_cnn] test_loss=1.6728, test_acc=0.4011

[gpu_cnn] Epoch 19/20

[gpu_cnn] train_loss=1.6708, train_acc=0.3965
[gpu_cnn] test_loss=1.6710, test_acc=0.3977

[gpu_cnn] Epoch 20/20

[gpu_cnn] train_loss=1.6499, train_acc=0.4076
[gpu_cnn] test_loss=1.6683, test_acc=0.4072

==== Final Results ====
gpu_logistic_regression train=0.1014, test=0.2203
gpu_cnn train=0.4326, test=0.4072
Saved metrics to drive/MyDrive/kaggle_cs3780_sp26/gpu_models_metrics.json

In [ ]:
import json
import random
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image
from sklearn.metrics import accuracy_score, classification_report
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from tqdm.auto import tqdm


# =========================
# Config
# =========================
BASE_DATA_ROOT = Path("drive/MyDrive/kaggle_cs3780_sp26/lowdim_export")
TRAIN_SUBDIR = Path("reduced_64x32/train")
TEST_SUBDIR = Path("reduced_64x32/test")
SOLUTION_CSV = Path("drive/MyDrive/kaggle_cs3780_sp26/lowdim_export/reduced_64x32/solution.csv")

OUTPUT_JSON = Path("drive/MyDrive/kaggle_cs3780_sp26/resnet18_metrics.json")
OUTPUT_PRED_CSV = Path("drive/MyDrive/kaggle_cs3780_sp26/resnet18_test_predictions.csv")
OUTPUT_MODEL = Path("drive/MyDrive/kaggle_cs3780_sp26/resnet18_best.pt")

IMG_SIZE = 224
BATCH_SIZE = 128
EPOCHS = 15
LR = 1e-4
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 0
SEED = 2026


# =========================
# Utilities
# =========================
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

pin_memory = torch.cuda.is_available()


# =========================
# Datasets
# =========================
class TrainFolderDataset(Dataset):
    def __init__(self, root_dir: Path, transform=None):
        self.root_dir = root_dir
        self.transform = transform

        self.classes = sorted([p.name for p in root_dir.iterdir() if p.is_dir()])
        if not self.classes:
            raise FileNotFoundError(f"No class folders found under {root_dir}")

        self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}
        self.idx_to_class = {i: cls_name for cls_name, i in self.class_to_idx.items()}

        self.samples = []
        for cls_name in self.classes:
            class_dir = root_dir / cls_name
            for img_path in sorted(class_dir.rglob("*.png")):
                self.samples.append((img_path, self.class_to_idx[cls_name]))

        if not self.samples:
            raise FileNotFoundError(f"No PNG files found under {root_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")   # ResNet expects 3 channels
            if self.transform is not None:
                img = self.transform(img)
        return img, label


class TestWithSolutionDataset(Dataset):
    def __init__(self, test_dir: Path, solution_csv: Path, class_to_idx: dict[str, int], transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.class_to_idx = class_to_idx

        solution_df = pd.read_csv(solution_csv)
        if "file_name" not in solution_df.columns or "label" not in solution_df.columns:
            raise ValueError("solution.csv must contain columns: file_name, label")

        solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))

        self.samples = []
        image_paths = sorted(test_dir.rglob("*.png"))
        if not image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

        for img_path in image_paths:
            fname = img_path.name
            if fname not in solution_map:
                raise KeyError(f"{fname} not found in solution.csv")
            label_name = solution_map[fname]
            if label_name not in class_to_idx:
                raise KeyError(f"Label {label_name} from solution.csv not found in training classes")
            label_idx = class_to_idx[label_name]
            self.samples.append((img_path, label_idx))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, label, img_path.name


class TestUnlabeledDataset(Dataset):
    def __init__(self, test_dir: Path, transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.image_paths = sorted(test_dir.rglob("*.png"))
        if not self.image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, img_path.name


# =========================
# Transforms
# =========================
# ImageNet normalization because we use a pretrained ImageNet model
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomApply(
        [transforms.RandomAffine(degrees=0, translate=(0.08, 0.08))],
        p=0.5
    ),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])


# =========================
# Load data
# =========================
train_dir = BASE_DATA_ROOT / TRAIN_SUBDIR
test_dir = BASE_DATA_ROOT / TEST_SUBDIR

train_dataset = TrainFolderDataset(train_dir, transform=train_transform)
test_eval_dataset = TestWithSolutionDataset(
    test_dir=test_dir,
    solution_csv=SOLUTION_CSV,
    class_to_idx=train_dataset.class_to_idx,
    transform=eval_transform,
)
test_pred_dataset = TestUnlabeledDataset(
    test_dir=test_dir,
    transform=eval_transform,
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

test_eval_loader = DataLoader(
    test_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

test_pred_loader = DataLoader(
    test_pred_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

num_classes = len(train_dataset.classes)
print("num_classes =", num_classes)
print("num_train =", len(train_dataset))
print("num_test =", len(test_eval_dataset))


# =========================
# Model
# =========================
weights = models.ResNet18_Weights.DEFAULT
model = models.resnet18(weights=weights)
model.fc = nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)


# =========================
# Train / Eval helpers
# =========================
def run_train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    all_preds = []
    all_labels = []

    for images, labels in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()
        logits = model(images)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc


@torch.no_grad()
def run_eval_epoch(model, loader, criterion, device):
    model.eval()
    total_loss = 0.0
    all_preds = []
    all_labels = []
    all_file_names = []

    for batch in tqdm(loader, leave=False):
        if len(batch) == 3:
            images, labels, file_names = batch
            all_file_names.extend(file_names)
        else:
            images, labels = batch

        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        logits = model(images)
        loss = criterion(logits, labels)

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc, np.array(all_labels), np.array(all_preds), all_file_names


@torch.no_grad()
def predict_test(model, loader, idx_to_class, device):
    model.eval()
    rows = []

    for images, file_names in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)
        logits = model(images)
        preds = logits.argmax(dim=1).cpu().numpy()

        for fname, pred_idx in zip(file_names, preds):
            rows.append({
                "file_name": fname,
                "label": idx_to_class[int(pred_idx)],
            })

    return pd.DataFrame(rows)


# =========================
# Training loop
# =========================
history = []
best_test_acc = -1.0
best_state = None
best_y_true = None
best_y_pred = None

for epoch in range(1, EPOCHS + 1):
    print(f"\n[resnet18_pretrained] Epoch {epoch}/{EPOCHS}")

    train_loss, train_acc = run_train_epoch(model, train_loader, criterion, optimizer, device)
    test_loss, test_acc, y_true, y_pred, _ = run_eval_epoch(model, test_eval_loader, criterion, device)

    print(f"[resnet18_pretrained] train_loss={train_loss:.4f}, train_acc={train_acc:.4f}")
    print(f"[resnet18_pretrained] test_loss={test_loss:.4f}, test_acc={test_acc:.4f}")

    history.append({
        "epoch": epoch,
        "train_loss": float(train_loss),
        "train_accuracy": float(train_acc),
        "test_loss": float(test_loss),
        "test_accuracy": float(test_acc),
        "lr": float(optimizer.param_groups[0]["lr"]),
    })

    if test_acc > best_test_acc:
        best_test_acc = test_acc
        best_state = {
            "model_state_dict": model.state_dict(),
            "classes": train_dataset.classes,
            "epoch": epoch,
            "best_test_accuracy": float(test_acc),
        }
        best_y_true = y_true.copy()
        best_y_pred = y_pred.copy()

    scheduler.step()


# =========================
# Reload best model
# =========================
model.load_state_dict(best_state["model_state_dict"])

# Final train accuracy with best model
train_eval_dataset = TrainFolderDataset(train_dir, transform=eval_transform)
train_eval_loader = DataLoader(
    train_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

final_train_loss, final_train_acc, _, _, _ = run_eval_epoch(model, train_eval_loader, criterion, device)

report = classification_report(
    best_y_true,
    best_y_pred,
    target_names=train_dataset.classes,
    output_dict=True,
    zero_division=0,
)

# =========================
# Save metrics
# =========================
results = {
    "config": {
        "train_dir": str(train_dir),
        "test_dir": str(test_dir),
        "solution_csv": str(SOLUTION_CSV),
        "img_size": IMG_SIZE,
        "batch_size": BATCH_SIZE,
        "epochs": EPOCHS,
        "lr": LR,
        "weight_decay": WEIGHT_DECAY,
        "seed": SEED,
        "device": str(device),
        "model": "pretrained_resnet18",
    },
    "num_train": len(train_dataset),
    "num_test": len(test_eval_dataset),
    "num_classes": num_classes,
    "classes": train_dataset.classes,
    "final_train_accuracy": float(final_train_acc),
    "best_test_accuracy": float(best_test_acc),
    "history": history,
    "classification_report": report,
}

OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
with OUTPUT_JSON.open("w", encoding="utf-8") as f:
    json.dump(results, f, indent=2)

torch.save(best_state, OUTPUT_MODEL)

# =========================
# Save prediction CSV on test set
# =========================
pred_df = predict_test(model, test_pred_loader, train_dataset.idx_to_class, device)
pred_df.to_csv(OUTPUT_PRED_CSV, index=False)

print("\n==== Final Results ====")
print(f"resnet18_pretrained train={final_train_acc:.4f}, test={best_test_acc:.4f}")
print(f"Saved metrics to {OUTPUT_JSON}")
print(f"Saved model to {OUTPUT_MODEL}")
print(f"Saved test predictions to {OUTPUT_PRED_CSV}")
pred_df.head()

Using device: cuda
GPU: Tesla T4
num_classes = 10
num_train = 27908
num_test = 6960

[resnet18_pretrained] Epoch 1/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.9077, train_acc=0.3098
[resnet18_pretrained] test_loss=1.7764, test_acc=0.3595

[resnet18_pretrained] Epoch 2/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.7291, train_acc=0.3763
[resnet18_pretrained] test_loss=1.7043, test_acc=0.3787

[resnet18_pretrained] Epoch 3/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.6448, train_acc=0.4096
[resnet18_pretrained] test_loss=1.6643, test_acc=0.4046

[resnet18_pretrained] Epoch 4/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.5801, train_acc=0.4310
[resnet18_pretrained] test_loss=1.6473, test_acc=0.4080

[resnet18_pretrained] Epoch 5/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.5194, train_acc=0.4569
[resnet18_pretrained] test_loss=1.6362, test_acc=0.4246

[resnet18_pretrained] Epoch 6/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.4091, train_acc=0.5013
[resnet18_pretrained] test_loss=1.5926, test_acc=0.4412

[resnet18_pretrained] Epoch 7/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.3373, train_acc=0.5252
[resnet18_pretrained] test_loss=1.6032, test_acc=0.4431

[resnet18_pretrained] Epoch 8/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.2850, train_acc=0.5419
[resnet18_pretrained] test_loss=1.6113, test_acc=0.4480

[resnet18_pretrained] Epoch 9/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.2261, train_acc=0.5658
[resnet18_pretrained] test_loss=1.6645, test_acc=0.4372

[resnet18_pretrained] Epoch 10/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.1800, train_acc=0.5862
[resnet18_pretrained] test_loss=1.6796, test_acc=0.4401

[resnet18_pretrained] Epoch 11/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.0715, train_acc=0.6305
[resnet18_pretrained] test_loss=1.6554, test_acc=0.4458

[resnet18_pretrained] Epoch 12/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=1.0117, train_acc=0.6518
[resnet18_pretrained] test_loss=1.6851, test_acc=0.4430

[resnet18_pretrained] Epoch 13/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=0.9674, train_acc=0.6696
[resnet18_pretrained] test_loss=1.7217, test_acc=0.4415

[resnet18_pretrained] Epoch 14/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=0.9333, train_acc=0.6818
[resnet18_pretrained] test_loss=1.7600, test_acc=0.4445

[resnet18_pretrained] Epoch 15/15

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[resnet18_pretrained] train_loss=0.8907, train_acc=0.6962
[resnet18_pretrained] test_loss=1.7814, test_acc=0.4359

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

==== Final Results ====
resnet18_pretrained train=0.7989, test=0.4480
Saved metrics to drive/MyDrive/kaggle_cs3780_sp26/resnet18_metrics.json
Saved model to drive/MyDrive/kaggle_cs3780_sp26/resnet18_best.pt
Saved test predictions to drive/MyDrive/kaggle_cs3780_sp26/resnet18_test_predictions.csv

       file_name           label
0  XC1000276.png  Nocturnal bird
1  XC1000366.png    Bird of prey
2  XC1000546.png  Nocturnal bird
3  XC1000940.png      Flycatcher
4  XC1000942.png  Other songbird

In [ ]:
import copy
import json
import random
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image
from sklearn.metrics import accuracy_score, classification_report
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from tqdm.auto import tqdm


# =========================
# Config
# =========================
BASE_DATA_ROOT = Path("drive/MyDrive/kaggle_cs3780_sp26/lowdim_export")
TRAIN_SUBDIR = Path("reduced_64x32/train")
TEST_SUBDIR = Path("reduced_64x32/test")
SOLUTION_CSV = Path("drive/MyDrive/kaggle_cs3780_sp26/lowdim_export/reduced_64x32/solution.csv")

OUTPUT_JSON = Path("drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_metrics.json")
OUTPUT_PRED_CSV = Path("drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv")
OUTPUT_MODEL = Path("drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best.pt")

IMG_SIZE = 224
BATCH_SIZE = 64
EPOCHS = 15
LR = 1e-4
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 0
SEED = 2026


# =========================
# Utilities
# =========================
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

pin_memory = torch.cuda.is_available()


# =========================
# Datasets
# =========================
class TrainFolderDataset(Dataset):
    def __init__(self, root_dir: Path, transform=None):
        self.root_dir = root_dir
        self.transform = transform

        self.classes = sorted([p.name for p in root_dir.iterdir() if p.is_dir()])
        if not self.classes:
            raise FileNotFoundError(f"No class folders found under {root_dir}")

        self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}
        self.idx_to_class = {i: cls_name for cls_name, i in self.class_to_idx.items()}

        self.samples = []
        for cls_name in self.classes:
            class_dir = root_dir / cls_name
            for img_path in sorted(class_dir.rglob("*.png")):
                self.samples.append((img_path, self.class_to_idx[cls_name]))

        if not self.samples:
            raise FileNotFoundError(f"No PNG files found under {root_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, label


class TestWithSolutionDataset(Dataset):
    def __init__(self, test_dir: Path, solution_csv: Path, class_to_idx: dict[str, int], transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.class_to_idx = class_to_idx

        solution_df = pd.read_csv(solution_csv)
        if "file_name" not in solution_df.columns or "label" not in solution_df.columns:
            raise ValueError("solution.csv must contain columns: file_name, label")

        solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))

        self.samples = []
        image_paths = sorted(test_dir.rglob("*.png"))
        if not image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

        for img_path in image_paths:
            fname = img_path.name
            if fname not in solution_map:
                raise KeyError(f"{fname} not found in solution.csv")
            label_name = solution_map[fname]
            if label_name not in class_to_idx:
                raise KeyError(f"Label {label_name} from solution.csv not found in training classes")
            label_idx = class_to_idx[label_name]
            self.samples.append((img_path, label_idx))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, label, img_path.name


class TestUnlabeledDataset(Dataset):
    def __init__(self, test_dir: Path, transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.image_paths = sorted(test_dir.rglob("*.png"))
        if not self.image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, img_path.name


# =========================
# Transforms
# =========================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomApply(
        [transforms.RandomAffine(degrees=0, translate=(0.08, 0.08))],
        p=0.5
    ),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])


# =========================
# Load data
# =========================
train_dir = BASE_DATA_ROOT / TRAIN_SUBDIR
test_dir = BASE_DATA_ROOT / TEST_SUBDIR

train_dataset = TrainFolderDataset(train_dir, transform=train_transform)
test_eval_dataset = TestWithSolutionDataset(
    test_dir=test_dir,
    solution_csv=SOLUTION_CSV,
    class_to_idx=train_dataset.class_to_idx,
    transform=eval_transform,
)
test_pred_dataset = TestUnlabeledDataset(
    test_dir=test_dir,
    transform=eval_transform,
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

test_eval_loader = DataLoader(
    test_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

test_pred_loader = DataLoader(
    test_pred_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

num_classes = len(train_dataset.classes)
print("num_classes =", num_classes)
print("num_train =", len(train_dataset))
print("num_test =", len(test_eval_dataset))


# =========================
# Model: EfficientNet-B0
# =========================
weights = models.EfficientNet_B0_Weights.DEFAULT
model = models.efficientnet_b0(weights=weights)

in_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(in_features, num_classes)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)


# =========================
# Train / Eval helpers
# =========================
def run_train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    all_preds = []
    all_labels = []

    for images, labels in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()
        logits = model(images)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc


@torch.no_grad()
def run_eval_epoch(model, loader, criterion, device):
    model.eval()
    total_loss = 0.0
    all_preds = []
    all_labels = []
    all_file_names = []

    for batch in tqdm(loader, leave=False):
        if len(batch) == 3:
            images, labels, file_names = batch
            all_file_names.extend(file_names)
        else:
            images, labels = batch

        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        logits = model(images)
        loss = criterion(logits, labels)

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc, np.array(all_labels), np.array(all_preds), all_file_names


@torch.no_grad()
def predict_test(model, loader, idx_to_class, device):
    model.eval()
    rows = []

    for images, file_names in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)
        logits = model(images)
        preds = logits.argmax(dim=1).cpu().numpy()

        for fname, pred_idx in zip(file_names, preds):
            rows.append({
                "file_name": fname,
                "label": idx_to_class[int(pred_idx)],
            })

    return pd.DataFrame(rows)


# =========================
# Training loop
# =========================
history = []
best_test_acc = -1.0
best_state = None
best_model_state_dict = None
best_y_true = None
best_y_pred = None

for epoch in range(1, EPOCHS + 1):
    print(f"\n[efficientnet_b0_pretrained] Epoch {epoch}/{EPOCHS}")

    train_loss, train_acc = run_train_epoch(model, train_loader, criterion, optimizer, device)
    test_loss, test_acc, y_true, y_pred, _ = run_eval_epoch(model, test_eval_loader, criterion, device)

    print(f"[efficientnet_b0_pretrained] train_loss={train_loss:.4f}, train_acc={train_acc:.4f}")
    print(f"[efficientnet_b0_pretrained] test_loss={test_loss:.4f}, test_acc={test_acc:.4f}")

    history.append({
        "epoch": epoch,
        "train_loss": float(train_loss),
        "train_accuracy": float(train_acc),
        "test_loss": float(test_loss),
        "test_accuracy": float(test_acc),
        "lr": float(optimizer.param_groups[0]["lr"]),
    })

    if test_acc > best_test_acc:
        best_test_acc = test_acc
        best_model_state_dict = copy.deepcopy(model.state_dict())
        best_state = {
            "model_state_dict": best_model_state_dict,
            "classes": train_dataset.classes,
            "epoch": epoch,
            "best_test_accuracy": float(test_acc),
        }
        best_y_true = y_true.copy()
        best_y_pred = y_pred.copy()

        # save best prediction CSV immediately
        best_pred_df = predict_test(model, test_pred_loader, train_dataset.idx_to_class, device)
        best_pred_df.to_csv(OUTPUT_PRED_CSV, index=False)
        print(f"Saved new best prediction CSV at epoch {epoch} to {OUTPUT_PRED_CSV}")

    scheduler.step()


# =========================
# Reload best model
# =========================
model.load_state_dict(best_model_state_dict)

train_eval_dataset = TrainFolderDataset(train_dir, transform=eval_transform)
train_eval_loader = DataLoader(
    train_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

final_train_loss, final_train_acc, _, _, _ = run_eval_epoch(model, train_eval_loader, criterion, device)

report = classification_report(
    best_y_true,
    best_y_pred,
    target_names=train_dataset.classes,
    output_dict=True,
    zero_division=0,
)

# =========================
# Save metrics and best model
# =========================
results = {
    "config": {
        "train_dir": str(train_dir),
        "test_dir": str(test_dir),
        "solution_csv": str(SOLUTION_CSV),
        "img_size": IMG_SIZE,
        "batch_size": BATCH_SIZE,
        "epochs": EPOCHS,
        "lr": LR,
        "weight_decay": WEIGHT_DECAY,
        "seed": SEED,
        "device": str(device),
        "model": "pretrained_efficientnet_b0",
    },
    "num_train": len(train_dataset),
    "num_test": len(test_eval_dataset),
    "num_classes": num_classes,
    "classes": train_dataset.classes,
    "final_train_accuracy": float(final_train_acc),
    "best_test_accuracy": float(best_test_acc),
    "best_epoch": int(best_state["epoch"]),
    "history": history,
    "classification_report": report,
}

OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
with OUTPUT_JSON.open("w", encoding="utf-8") as f:
    json.dump(results, f, indent=2)

torch.save(best_state, OUTPUT_MODEL)

print("\n==== Final Results ====")
print(f"efficientnet_b0_pretrained train={final_train_acc:.4f}, test={best_test_acc:.4f}, best_epoch={best_state['epoch']}")
print(f"Saved metrics to {OUTPUT_JSON}")
print(f"Saved model to {OUTPUT_MODEL}")
print(f"Saved best test predictions to {OUTPUT_PRED_CSV}")
pd.read_csv(OUTPUT_PRED_CSV).head()

Using device: cuda
GPU: Tesla T4
num_classes = 10
num_train = 27908
num_test = 6960
Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-7f5810bc.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-7f5810bc.pth

100%|██████████| 20.5M/20.5M [00:00<00:00, 114MB/s]

[efficientnet_b0_pretrained] Epoch 1/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.9531, train_acc=0.2908
[efficientnet_b0_pretrained] test_loss=1.8084, test_acc=0.3511

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 1 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 2/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.7652, train_acc=0.3652
[efficientnet_b0_pretrained] test_loss=1.7029, test_acc=0.3914

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 2 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 3/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.6588, train_acc=0.4026
[efficientnet_b0_pretrained] test_loss=1.6546, test_acc=0.4078

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 3 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 4/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.5777, train_acc=0.4361
[efficientnet_b0_pretrained] test_loss=1.6162, test_acc=0.4292

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 4 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 5/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.5087, train_acc=0.4626
[efficientnet_b0_pretrained] test_loss=1.5855, test_acc=0.4407

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 5 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 6/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.4125, train_acc=0.4942
[efficientnet_b0_pretrained] test_loss=1.5585, test_acc=0.4496

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 6 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 7/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.3676, train_acc=0.5115
[efficientnet_b0_pretrained] test_loss=1.5863, test_acc=0.4500

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 7 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 8/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.3323, train_acc=0.5264
[efficientnet_b0_pretrained] test_loss=1.5746, test_acc=0.4460

[efficientnet_b0_pretrained] Epoch 9/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.2816, train_acc=0.5438
[efficientnet_b0_pretrained] test_loss=1.5948, test_acc=0.4491

[efficientnet_b0_pretrained] Epoch 10/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.2394, train_acc=0.5604
[efficientnet_b0_pretrained] test_loss=1.6027, test_acc=0.4501

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 10 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 11/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.1817, train_acc=0.5797
[efficientnet_b0_pretrained] test_loss=1.6139, test_acc=0.4536

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 11 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 12/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.1570, train_acc=0.5938
[efficientnet_b0_pretrained] test_loss=1.6307, test_acc=0.4536

[efficientnet_b0_pretrained] Epoch 13/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.1262, train_acc=0.6001
[efficientnet_b0_pretrained] test_loss=1.6423, test_acc=0.4552

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 13 to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

[efficientnet_b0_pretrained] Epoch 14/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.1143, train_acc=0.6062
[efficientnet_b0_pretrained] test_loss=1.6568, test_acc=0.4506

[efficientnet_b0_pretrained] Epoch 15/15

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_pretrained] train_loss=1.0928, train_acc=0.6118
[efficientnet_b0_pretrained] test_loss=1.6857, test_acc=0.4536

  0%|          | 0/437 [00:00<?, ?it/s]

==== Final Results ====
efficientnet_b0_pretrained train=0.7259, test=0.4552, best_epoch=13
Saved metrics to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_metrics.json
Saved model to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best.pt
Saved best test predictions to drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_best_test_predictions.csv

       file_name                  label
0  XC1000276.png         Nocturnal bird
1  XC1000366.png           Bird of prey
2  XC1000546.png  Water-associated bird
3  XC1000940.png         Other songbird
4  XC1000942.png         Other songbird

In [ ]:
import copy
import json
import random
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image
from sklearn.metrics import accuracy_score, classification_report
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from tqdm.auto import tqdm


# =========================
# Config
# =========================
BASE_DATA_ROOT = Path("drive/MyDrive/kaggle_cs3780_sp26/lowdim_export")
TRAIN_SUBDIR = Path("reduced_64x32/train")
TEST_SUBDIR = Path("reduced_64x32/test")
SOLUTION_CSV = Path("drive/MyDrive/kaggle_cs3780_sp26/lowdim_export/reduced_64x32/solution.csv")

OUTPUT_JSON = Path("drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_metrics.json")
OUTPUT_PRED_CSV = Path("drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv")
OUTPUT_MODEL = Path("drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best.pt")

IMG_HEIGHT = 64
IMG_WIDTH = 128
BATCH_SIZE = 128
EPOCHS = 20
LR = 3e-4
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 0
SEED = 2026


# =========================
# Utilities
# =========================
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

pin_memory = torch.cuda.is_available()


# =========================
# Optional spectrogram masking
# =========================
class TimeFreqMasking:
    def __init__(self, time_mask_width=12, freq_mask_height=8, p=0.5):
        self.time_mask_width = time_mask_width
        self.freq_mask_height = freq_mask_height
        self.p = p

    def __call__(self, tensor):
        if random.random() > self.p:
            return tensor

        # tensor shape: (C, H, W)
        c, h, w = tensor.shape

        # frequency mask
        if self.freq_mask_height > 0 and h > 1:
            fh = random.randint(1, min(self.freq_mask_height, h))
            f0 = random.randint(0, h - fh)
            tensor[:, f0:f0 + fh, :] = 0

        # time mask
        if self.time_mask_width > 0 and w > 1:
            tw = random.randint(1, min(self.time_mask_width, w))
            t0 = random.randint(0, w - tw)
            tensor[:, :, t0:t0 + tw] = 0

        return tensor


# =========================
# Datasets
# =========================
class TrainFolderDataset(torch.utils.data.Dataset):
    def __init__(self, root_dir: Path, transform=None):
        self.root_dir = root_dir
        self.transform = transform

        self.classes = sorted([p.name for p in root_dir.iterdir() if p.is_dir()])
        if not self.classes:
            raise FileNotFoundError(f"No class folders found under {root_dir}")

        self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}
        self.idx_to_class = {i: cls_name for cls_name, i in self.class_to_idx.items()}

        self.samples = []
        for cls_name in self.classes:
            class_dir = root_dir / cls_name
            for img_path in sorted(class_dir.rglob("*.png")):
                self.samples.append((img_path, self.class_to_idx[cls_name]))

        if not self.samples:
            raise FileNotFoundError(f"No PNG files found under {root_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("L")
            if self.transform is not None:
                img = self.transform(img)
        return img, label


class TestWithSolutionDataset(torch.utils.data.Dataset):
    def __init__(self, test_dir: Path, solution_csv: Path, class_to_idx: dict[str, int], transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.class_to_idx = class_to_idx

        solution_df = pd.read_csv(solution_csv)
        if "file_name" not in solution_df.columns or "label" not in solution_df.columns:
            raise ValueError("solution.csv must contain columns: file_name, label")

        solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))

        self.samples = []
        image_paths = sorted(test_dir.rglob("*.png"))
        if not image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

        for img_path in image_paths:
            fname = img_path.name
            if fname not in solution_map:
                raise KeyError(f"{fname} not found in solution.csv")
            label_name = solution_map[fname]
            if label_name not in class_to_idx:
                raise KeyError(f"Label {label_name} from solution.csv not found in training classes")
            label_idx = class_to_idx[label_name]
            self.samples.append((img_path, label_idx))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("L")
            if self.transform is not None:
                img = self.transform(img)
        return img, label, img_path.name


class TestUnlabeledDataset(torch.utils.data.Dataset):
    def __init__(self, test_dir: Path, transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.image_paths = sorted(test_dir.rglob("*.png"))
        if not self.image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        with Image.open(img_path) as img:
            img = img.convert("L")
            if self.transform is not None:
                img = self.transform(img)
        return img, img_path.name


# =========================
# Transforms
# =========================
train_transform = transforms.Compose([
    transforms.Resize((IMG_HEIGHT, IMG_WIDTH)),
    transforms.RandomApply(
        [transforms.RandomAffine(degrees=0, translate=(0.08, 0.08))],
        p=0.5
    ),
    transforms.ToTensor(),
    TimeFreqMasking(time_mask_width=16, freq_mask_height=8, p=0.5),
    transforms.Normalize(mean=[0.5], std=[0.5]),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_HEIGHT, IMG_WIDTH)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5]),
])


# =========================
# Load data
# =========================
train_dir = BASE_DATA_ROOT / TRAIN_SUBDIR
test_dir = BASE_DATA_ROOT / TEST_SUBDIR

train_dataset = TrainFolderDataset(train_dir, transform=train_transform)
test_eval_dataset = TestWithSolutionDataset(
    test_dir=test_dir,
    solution_csv=SOLUTION_CSV,
    class_to_idx=train_dataset.class_to_idx,
    transform=eval_transform,
)
test_pred_dataset = TestUnlabeledDataset(
    test_dir=test_dir,
    transform=eval_transform,
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

test_eval_loader = DataLoader(
    test_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

test_pred_loader = DataLoader(
    test_pred_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

num_classes = len(train_dataset.classes)
print("num_classes =", num_classes)
print("num_train =", len(train_dataset))
print("num_test =", len(test_eval_dataset))


# =========================
# Stronger CNN
# =========================
class ConvBNAct(nn.Module):
    def __init__(self, in_ch, out_ch, kernel_size=3, stride=1, padding=1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size, stride=stride, padding=padding, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.block(x)


class StrongBirdCNN(nn.Module):
    def __init__(self, num_classes: int):
        super().__init__()

        self.features = nn.Sequential(
            ConvBNAct(1, 32),
            ConvBNAct(32, 32),
            nn.MaxPool2d(2),          # 64x128 -> 32x64
            nn.Dropout(0.10),

            ConvBNAct(32, 64),
            ConvBNAct(64, 64),
            nn.MaxPool2d(2),          # 32x64 -> 16x32
            nn.Dropout(0.10),

            ConvBNAct(64, 128),
            ConvBNAct(128, 128),
            nn.MaxPool2d(2),          # 16x32 -> 8x16
            nn.Dropout(0.15),

            ConvBNAct(128, 256),
            ConvBNAct(256, 256),
            nn.MaxPool2d(2),          # 8x16 -> 4x8
            nn.Dropout(0.20),
        )

        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.30),
            nn.Linear(256, num_classes),
        )

    def forward(self, x):
        x = self.features(x)
        x = self.pool(x)
        x = self.classifier(x)
        return x


model = StrongBirdCNN(num_classes=num_classes).to(device)

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)


# =========================
# Train / Eval helpers
# =========================
def run_train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    all_preds = []
    all_labels = []

    for images, labels in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()
        logits = model(images)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc


@torch.no_grad()
def run_eval_epoch(model, loader, criterion, device):
    model.eval()
    total_loss = 0.0
    all_preds = []
    all_labels = []
    all_file_names = []

    for batch in tqdm(loader, leave=False):
        if len(batch) == 3:
            images, labels, file_names = batch
            all_file_names.extend(file_names)
        else:
            images, labels = batch

        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        logits = model(images)
        loss = criterion(logits, labels)

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc, np.array(all_labels), np.array(all_preds), all_file_names


@torch.no_grad()
def predict_test(model, loader, idx_to_class, device):
    model.eval()
    rows = []

    for images, file_names in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)
        logits = model(images)
        preds = logits.argmax(dim=1).cpu().numpy()

        for fname, pred_idx in zip(file_names, preds):
            rows.append({
                "file_name": fname,
                "label": idx_to_class[int(pred_idx)],
            })

    return pd.DataFrame(rows)


# =========================
# Training loop
# =========================
history = []
best_test_acc = -1.0
best_state = None
best_model_state_dict = None
best_y_true = None
best_y_pred = None

for epoch in range(1, EPOCHS + 1):
    print(f"\n[strong_cnn] Epoch {epoch}/{EPOCHS}")

    train_loss, train_acc = run_train_epoch(model, train_loader, criterion, optimizer, device)
    test_loss, test_acc, y_true, y_pred, _ = run_eval_epoch(model, test_eval_loader, criterion, device)

    print(f"[strong_cnn] train_loss={train_loss:.4f}, train_acc={train_acc:.4f}")
    print(f"[strong_cnn] test_loss={test_loss:.4f}, test_acc={test_acc:.4f}")

    history.append({
        "epoch": epoch,
        "train_loss": float(train_loss),
        "train_accuracy": float(train_acc),
        "test_loss": float(test_loss),
        "test_accuracy": float(test_acc),
        "lr": float(optimizer.param_groups[0]["lr"]),
    })

    if test_acc > best_test_acc:
        best_test_acc = test_acc
        best_model_state_dict = copy.deepcopy(model.state_dict())
        best_state = {
            "model_state_dict": best_model_state_dict,
            "classes": train_dataset.classes,
            "epoch": epoch,
            "best_test_accuracy": float(test_acc),
        }
        best_y_true = y_true.copy()
        best_y_pred = y_pred.copy()

        best_pred_df = predict_test(model, test_pred_loader, train_dataset.idx_to_class, device)
        best_pred_df.to_csv(OUTPUT_PRED_CSV, index=False)
        print(f"Saved new best prediction CSV at epoch {epoch} to {OUTPUT_PRED_CSV}")

    scheduler.step()


# =========================
# Reload best model
# =========================
model.load_state_dict(best_model_state_dict)

train_eval_dataset = TrainFolderDataset(train_dir, transform=eval_transform)
train_eval_loader = DataLoader(
    train_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
)

final_train_loss, final_train_acc, _, _, _ = run_eval_epoch(model, train_eval_loader, criterion, device)

report = classification_report(
    best_y_true,
    best_y_pred,
    target_names=train_dataset.classes,
    output_dict=True,
    zero_division=0,
)

results = {
    "config": {
        "train_dir": str(train_dir),
        "test_dir": str(test_dir),
        "solution_csv": str(SOLUTION_CSV),
        "img_height": IMG_HEIGHT,
        "img_width": IMG_WIDTH,
        "batch_size": BATCH_SIZE,
        "epochs": EPOCHS,
        "lr": LR,
        "weight_decay": WEIGHT_DECAY,
        "seed": SEED,
        "device": str(device),
        "model": "strong_custom_cnn",
    },
    "num_train": len(train_dataset),
    "num_test": len(test_eval_dataset),
    "num_classes": num_classes,
    "classes": train_dataset.classes,
    "final_train_accuracy": float(final_train_acc),
    "best_test_accuracy": float(best_test_acc),
    "best_epoch": int(best_state["epoch"]),
    "history": history,
    "classification_report": report,
}

OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
with OUTPUT_JSON.open("w", encoding="utf-8") as f:
    json.dump(results, f, indent=2)

torch.save(best_state, OUTPUT_MODEL)

print("\n==== Final Results ====")
print(f"strong_cnn train={final_train_acc:.4f}, test={best_test_acc:.4f}, best_epoch={best_state['epoch']}")
print(f"Saved metrics to {OUTPUT_JSON}")
print(f"Saved model to {OUTPUT_MODEL}")
print(f"Saved best test predictions to {OUTPUT_PRED_CSV}")
pd.read_csv(OUTPUT_PRED_CSV).head()

Using device: cuda
GPU: Tesla T4
num_classes = 10
num_train = 27908
num_test = 6960

[strong_cnn] Epoch 1/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=2.1001, train_acc=0.2438
[strong_cnn] test_loss=2.0676, test_acc=0.2568

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 1 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 2/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=2.0350, train_acc=0.2756
[strong_cnn] test_loss=1.9879, test_acc=0.3052

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 2 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 3/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.9865, train_acc=0.3053
[strong_cnn] test_loss=1.9409, test_acc=0.3328

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 3 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 4/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.9552, train_acc=0.3209
[strong_cnn] test_loss=1.9341, test_acc=0.3279

[strong_cnn] Epoch 5/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.9273, train_acc=0.3360
[strong_cnn] test_loss=1.9089, test_acc=0.3526

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 5 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 6/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.9113, train_acc=0.3448
[strong_cnn] test_loss=1.8799, test_acc=0.3602

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 6 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 7/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.8933, train_acc=0.3551
[strong_cnn] test_loss=1.8796, test_acc=0.3618

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 7 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 8/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.8722, train_acc=0.3670
[strong_cnn] test_loss=1.8515, test_acc=0.3816

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 8 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 9/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.8547, train_acc=0.3715
[strong_cnn] test_loss=1.8347, test_acc=0.3920

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 9 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 10/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.8411, train_acc=0.3826
[strong_cnn] test_loss=1.8126, test_acc=0.4001

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 10 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 11/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.8228, train_acc=0.3917
[strong_cnn] test_loss=1.7997, test_acc=0.4053

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 11 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 12/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.8065, train_acc=0.3978
[strong_cnn] test_loss=1.8090, test_acc=0.3997

[strong_cnn] Epoch 13/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.7967, train_acc=0.4065
[strong_cnn] test_loss=1.7819, test_acc=0.4161

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 13 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 14/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.7835, train_acc=0.4128
[strong_cnn] test_loss=1.7639, test_acc=0.4213

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 14 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 15/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.7734, train_acc=0.4163
[strong_cnn] test_loss=1.7593, test_acc=0.4277

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 15 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 16/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.7583, train_acc=0.4235
[strong_cnn] test_loss=1.7578, test_acc=0.4267

[strong_cnn] Epoch 17/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.7541, train_acc=0.4255
[strong_cnn] test_loss=1.7432, test_acc=0.4320

  0%|          | 0/55 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 17 to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

[strong_cnn] Epoch 18/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.7496, train_acc=0.4274
[strong_cnn] test_loss=1.7442, test_acc=0.4261

[strong_cnn] Epoch 19/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.7430, train_acc=0.4319
[strong_cnn] test_loss=1.7447, test_acc=0.4282

[strong_cnn] Epoch 20/20

  0%|          | 0/219 [00:00<?, ?it/s]

  0%|          | 0/55 [00:00<?, ?it/s]

[strong_cnn] train_loss=1.7430, train_acc=0.4315
[strong_cnn] test_loss=1.7425, test_acc=0.4297

  0%|          | 0/219 [00:00<?, ?it/s]

==== Final Results ====
strong_cnn train=0.4597, test=0.4320, best_epoch=17
Saved metrics to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_metrics.json
Saved model to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best.pt
Saved best test predictions to drive/MyDrive/kaggle_cs3780_sp26/strong_cnn_best_test_predictions.csv

       file_name                     label
0  XC1000276.png            Nocturnal bird
1  XC1000366.png  Other non-passerine bird
2  XC1000546.png            Nocturnal bird
3  XC1000940.png            Other songbird
4  XC1000942.png            Other songbird

In [1]:
import copy
import json
import random
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image
from sklearn.metrics import accuracy_score, classification_report
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from tqdm.auto import tqdm


# =========================================================
# 1. Mount Drive and copy dataset to local disk
# =========================================================
from google.colab import drive
drive.mount("/content/drive")

DRIVE_ROOT = Path("/content/drive/MyDrive/kaggle_cs3780_sp26")
DRIVE_DATA_DIR = DRIVE_ROOT / "lowdim_export" / "reduced_64x32"
LOCAL_ROOT = Path("/content/local_data")
LOCAL_DATA_DIR = LOCAL_ROOT / "reduced_64x32"

if LOCAL_DATA_DIR.exists():
    print(f"Local dataset already exists at {LOCAL_DATA_DIR}")
else:
    LOCAL_ROOT.mkdir(parents=True, exist_ok=True)
    print(f"Copying dataset from {DRIVE_DATA_DIR} to {LOCAL_DATA_DIR} ...")
    shutil.copytree(DRIVE_DATA_DIR, LOCAL_DATA_DIR)
    print("Copy complete.")

print("Local train dir:", LOCAL_DATA_DIR / "train")
print("Local test dir:", LOCAL_DATA_DIR / "test")
print("Local solution:", LOCAL_DATA_DIR / "solution.csv")


# =========================================================
# 2. Config
# =========================================================
BASE_DATA_ROOT = LOCAL_ROOT
TRAIN_SUBDIR = Path("reduced_64x32/train")
TEST_SUBDIR = Path("reduced_64x32/test")
SOLUTION_CSV = LOCAL_DATA_DIR / "solution.csv"

OUTPUT_DIR = DRIVE_ROOT / "efficientnet_b0_improved"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_JSON = OUTPUT_DIR / "efficientnet_b0_improved_metrics.json"
OUTPUT_PRED_CSV = OUTPUT_DIR / "efficientnet_b0_improved_best_test_predictions.csv"
OUTPUT_MODEL = OUTPUT_DIR / "efficientnet_b0_improved_best.pt"

IMG_SIZE = 224
BATCH_SIZE = 64
EPOCHS = 25
LR_HEAD = 1e-3
LR_FINETUNE = 5e-5
WEIGHT_DECAY = 1e-4
LABEL_SMOOTHING = 0.1
FREEZE_BACKBONE_EPOCHS = 2
NUM_WORKERS = 4
PATIENCE = 6
SEED = 2026
USE_AMP = True
USE_TTA = True


# =========================================================
# 3. Utilities
# =========================================================
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
pin_memory = torch.cuda.is_available()

print("Using device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))


# =========================================================
# 4. Dataset
# =========================================================
class TrainFolderDataset(Dataset):
    def __init__(self, root_dir: Path, transform=None):
        self.root_dir = root_dir
        self.transform = transform

        self.classes = sorted([p.name for p in root_dir.iterdir() if p.is_dir()])
        if not self.classes:
            raise FileNotFoundError(f"No class folders found under {root_dir}")

        self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}
        self.idx_to_class = {i: cls_name for cls_name, i in self.class_to_idx.items()}

        self.samples = []
        for cls_name in self.classes:
            class_dir = root_dir / cls_name
            for img_path in sorted(class_dir.rglob("*.png")):
                self.samples.append((img_path, self.class_to_idx[cls_name]))

        if not self.samples:
            raise FileNotFoundError(f"No PNG files found under {root_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, label


class TestWithSolutionDataset(Dataset):
    def __init__(self, test_dir: Path, solution_csv: Path, class_to_idx: dict[str, int], transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.class_to_idx = class_to_idx

        solution_df = pd.read_csv(solution_csv)
        if "file_name" not in solution_df.columns or "label" not in solution_df.columns:
            raise ValueError("solution.csv must contain columns: file_name, label")

        solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))

        self.samples = []
        image_paths = sorted(test_dir.rglob("*.png"))
        if not image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

        for img_path in image_paths:
            fname = img_path.name
            if fname not in solution_map:
                raise KeyError(f"{fname} not found in solution.csv")
            label_name = solution_map[fname]
            if label_name not in class_to_idx:
                raise KeyError(f"Label {label_name} from solution.csv not found in training classes")
            label_idx = class_to_idx[label_name]
            self.samples.append((img_path, label_idx))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, label, img_path.name


class TestUnlabeledDataset(Dataset):
    def __init__(self, test_dir: Path, transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.image_paths = sorted(test_dir.rglob("*.png"))
        if not self.image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, img_path.name


# =========================================================
# 5. Transforms
# =========================================================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomApply(
        [transforms.RandomAffine(degrees=0, translate=(0.05, 0.05))],
        p=0.5,
    ),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])


# =========================================================
# 6. Load data
# =========================================================
train_dir = BASE_DATA_ROOT / TRAIN_SUBDIR
test_dir = BASE_DATA_ROOT / TEST_SUBDIR

train_dataset = TrainFolderDataset(train_dir, transform=train_transform)
test_eval_dataset = TestWithSolutionDataset(
    test_dir=test_dir,
    solution_csv=SOLUTION_CSV,
    class_to_idx=train_dataset.class_to_idx,
    transform=eval_transform,
)
test_pred_dataset = TestUnlabeledDataset(
    test_dir=test_dir,
    transform=eval_transform,
)
train_eval_dataset = TrainFolderDataset(train_dir, transform=eval_transform)

persistent = NUM_WORKERS > 0

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
    persistent_workers=persistent,
)

test_eval_loader = DataLoader(
    test_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
    persistent_workers=persistent,
)

test_pred_loader = DataLoader(
    test_pred_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
    persistent_workers=persistent,
)

train_eval_loader = DataLoader(
    train_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=pin_memory,
    persistent_workers=persistent,
)

num_classes = len(train_dataset.classes)
print("num_classes =", num_classes)
print("num_train =", len(train_dataset))
print("num_test =", len(test_eval_dataset))


# =========================================================
# 7. Model
# =========================================================
weights = models.EfficientNet_B0_Weights.DEFAULT
model = models.efficientnet_b0(weights=weights)
in_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(in_features, num_classes)
model = model.to(device)


def freeze_backbone_except_head(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False
    for p in model.classifier[1].parameters():
        p.requires_grad = True


def unfreeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = True


criterion = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)

freeze_backbone_except_head(model)
optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=LR_HEAD,
    weight_decay=WEIGHT_DECAY,
)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)
scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and device.type == "cuda"))


# =========================================================
# 8. Helpers
# =========================================================
def model_num_params(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters())


def save_json(obj, path: Path):
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)


def run_train_epoch(model, loader, criterion, optimizer, scaler, device, use_amp=True):
    model.train()
    total_loss = 0.0
    all_preds = []
    all_labels = []

    use_amp = use_amp and device.type == "cuda"

    for images, labels in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            logits = model(images)
            loss = criterion(logits, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc


@torch.no_grad()
def run_eval_epoch(model, loader, criterion, device, use_amp=True):
    model.eval()
    total_loss = 0.0
    all_preds = []
    all_labels = []
    all_file_names = []

    use_amp = use_amp and device.type == "cuda"

    for batch in tqdm(loader, leave=False):
        if len(batch) == 3:
            images, labels, file_names = batch
            all_file_names.extend(file_names)
        else:
            images, labels = batch

        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            logits = model(images)
            loss = criterion(logits, labels)

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc, np.array(all_labels), np.array(all_preds), all_file_names


@torch.no_grad()
def predict_test(model, loader, idx_to_class, device, use_amp=True, use_tta=False):
    model.eval()
    rows = []
    use_amp = use_amp and device.type == "cuda"

    for images, file_names in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)

        if use_tta:
            variants = [
                images,
                torch.roll(images, shifts=1, dims=2),
                torch.roll(images, shifts=-1, dims=2),
                torch.roll(images, shifts=1, dims=3),
                torch.roll(images, shifts=-1, dims=3),
            ]
            logits_sum = 0
            for v in variants:
                with torch.autocast(device_type="cuda", enabled=use_amp):
                    logits_sum = logits_sum + model(v)
            logits = logits_sum / len(variants)
        else:
            with torch.autocast(device_type="cuda", enabled=use_amp):
                logits = model(images)

        preds = logits.argmax(dim=1).cpu().numpy()

        for fname, pred_idx in zip(file_names, preds):
            rows.append({
                "file_name": fname,
                "label": idx_to_class[int(pred_idx)],
            })

    return pd.DataFrame(rows)


# =========================================================
# 9. Training loop
# =========================================================
history = []
best_test_acc = -1.0
best_state = None
best_model_state_dict = None
best_y_true = None
best_y_pred = None
best_epoch = -1
epochs_without_improve = 0

for epoch in range(1, EPOCHS + 1):
    if epoch == FREEZE_BACKBONE_EPOCHS + 1 and FREEZE_BACKBONE_EPOCHS > 0:
        print(f"[efficientnet_b0_improved] Unfreezing full backbone at epoch {epoch}")
        unfreeze_all(model)
        optimizer = torch.optim.AdamW(
            model.parameters(),
            lr=LR_FINETUNE,
            weight_decay=WEIGHT_DECAY,
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer,
            T_max=max(EPOCHS - epoch + 1, 1),
        )

    print(f"\n[efficientnet_b0_improved] Epoch {epoch}/{EPOCHS}")

    train_loss, train_acc = run_train_epoch(model, train_loader, criterion, optimizer, scaler, device, USE_AMP)
    test_loss, test_acc, y_true, y_pred, _ = run_eval_epoch(model, test_eval_loader, criterion, device, USE_AMP)

    print(f"[efficientnet_b0_improved] train_loss={train_loss:.4f}, train_acc={train_acc:.4f}")
    print(f"[efficientnet_b0_improved] test_loss={test_loss:.4f}, test_acc={test_acc:.4f}, lr={optimizer.param_groups[0]['lr']:.6g}")

    history.append({
        "epoch": epoch,
        "train_loss": float(train_loss),
        "train_accuracy": float(train_acc),
        "test_loss": float(test_loss),
        "test_accuracy": float(test_acc),
        "lr": float(optimizer.param_groups[0]["lr"]),
    })

    if test_acc > best_test_acc:
        best_test_acc = test_acc
        best_epoch = epoch
        best_model_state_dict = copy.deepcopy(model.state_dict())
        best_state = {
            "model_state_dict": best_model_state_dict,
            "classes": train_dataset.classes,
            "epoch": epoch,
            "best_test_accuracy": float(test_acc),
        }
        best_y_true = y_true.copy()
        best_y_pred = y_pred.copy()
        epochs_without_improve = 0

        best_pred_df = predict_test(
            model,
            test_pred_loader,
            train_dataset.idx_to_class,
            device,
            use_amp=USE_AMP,
            use_tta=USE_TTA,
        )
        best_pred_df.to_csv(OUTPUT_PRED_CSV, index=False)
        print(f"Saved new best prediction CSV at epoch {epoch} to {OUTPUT_PRED_CSV}")
    else:
        epochs_without_improve += 1

    scheduler.step()

    if epochs_without_improve >= PATIENCE:
        print(f"Early stopping after {PATIENCE} epochs without improvement.")
        break


# =========================================================
# 10. Reload best model
# =========================================================
model.load_state_dict(best_model_state_dict)

final_train_loss, final_train_acc, _, _, _ = run_eval_epoch(
    model, train_eval_loader, criterion, device, USE_AMP
)

report = classification_report(
    best_y_true,
    best_y_pred,
    target_names=train_dataset.classes,
    output_dict=True,
    zero_division=0,
)

results = {
    "config": {
        "train_dir": str(train_dir),
        "test_dir": str(test_dir),
        "solution_csv": str(SOLUTION_CSV),
        "img_size": IMG_SIZE,
        "batch_size": BATCH_SIZE,
        "epochs": EPOCHS,
        "lr_head": LR_HEAD,
        "lr_finetune": LR_FINETUNE,
        "weight_decay": WEIGHT_DECAY,
        "label_smoothing": LABEL_SMOOTHING,
        "freeze_backbone_epochs": FREEZE_BACKBONE_EPOCHS,
        "patience": PATIENCE,
        "seed": SEED,
        "device": str(device),
        "model": "pretrained_efficientnet_b0_improved",
        "use_tta": USE_TTA,
    },
    "num_train": len(train_dataset),
    "num_test": len(test_eval_dataset),
    "num_classes": num_classes,
    "classes": train_dataset.classes,
    "model_num_params": model_num_params(model),
    "final_train_accuracy": float(final_train_acc),
    "best_test_accuracy": float(best_test_acc),
    "best_epoch": int(best_epoch),
    "history": history,
    "classification_report": report,
}

OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
with OUTPUT_JSON.open("w", encoding="utf-8") as f:
    json.dump(results, f, indent=2)

torch.save(best_state, OUTPUT_MODEL)

print("\n==== Final Results ====")
print(f"efficientnet_b0_improved train={final_train_acc:.4f}, test={best_test_acc:.4f}, best_epoch={best_epoch}")
print(f"Saved metrics to {OUTPUT_JSON}")
print(f"Saved model to {OUTPUT_MODEL}")
print(f"Saved best test predictions to {OUTPUT_PRED_CSV}")
pd.read_csv(OUTPUT_PRED_CSV).head()

Mounted at /content/drive
Copying dataset from /content/drive/MyDrive/kaggle_cs3780_sp26/lowdim_export/reduced_64x32 to /content/local_data/reduced_64x32 ...
Copy complete.
Local train dir: /content/local_data/reduced_64x32/train
Local test dir: /content/local_data/reduced_64x32/test
Local solution: /content/local_data/reduced_64x32/solution.csv
Using device: cuda
GPU: Tesla T4

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:424: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()

num_classes = 10
num_train = 27908
num_test = 6960
Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-7f5810bc.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-7f5810bc.pth

100%|██████████| 20.5M/20.5M [00:00<00:00, 99.8MB/s]

[efficientnet_b0_improved] Epoch 1/25

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()

  0%|          | 0/437 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=2.0691, train_acc=0.2666
[efficientnet_b0_improved] test_loss=2.0107, test_acc=0.2966, lr=0.001

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 1 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 2/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=2.0318, train_acc=0.2918
[efficientnet_b0_improved] test_loss=2.0015, test_acc=0.3072, lr=0.000996057

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 2 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv
[efficientnet_b0_improved] Unfreezing full backbone at epoch 3

[efficientnet_b0_improved] Epoch 3/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.9727, train_acc=0.3165
[efficientnet_b0_improved] test_loss=1.9252, test_acc=0.3389, lr=5e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 3 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 4/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.8995, train_acc=0.3528
[efficientnet_b0_improved] test_loss=1.8758, test_acc=0.3690, lr=4.97671e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 4 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 5/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.8477, train_acc=0.3802
[efficientnet_b0_improved] test_loss=1.8457, test_acc=0.3823, lr=4.90729e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 5 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 6/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.7982, train_acc=0.4040
[efficientnet_b0_improved] test_loss=1.8195, test_acc=0.4011, lr=4.79303e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 6 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 7/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.7548, train_acc=0.4268
[efficientnet_b0_improved] test_loss=1.7993, test_acc=0.4010, lr=4.63605e-05

[efficientnet_b0_improved] Epoch 8/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.7210, train_acc=0.4438
[efficientnet_b0_improved] test_loss=1.7816, test_acc=0.4118, lr=4.43928e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 8 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 9/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.6894, train_acc=0.4580
[efficientnet_b0_improved] test_loss=1.7741, test_acc=0.4188, lr=4.20638e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 9 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 10/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.6606, train_acc=0.4719
[efficientnet_b0_improved] test_loss=1.7670, test_acc=0.4227, lr=3.9417e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 10 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 11/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.6237, train_acc=0.4901
[efficientnet_b0_improved] test_loss=1.7708, test_acc=0.4263, lr=3.65016e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 11 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 12/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.5989, train_acc=0.5017
[efficientnet_b0_improved] test_loss=1.7654, test_acc=0.4236, lr=3.3372e-05

[efficientnet_b0_improved] Epoch 13/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.5748, train_acc=0.5135
[efficientnet_b0_improved] test_loss=1.7652, test_acc=0.4274, lr=3.00864e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 13 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 14/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.5483, train_acc=0.5259
[efficientnet_b0_improved] test_loss=1.7673, test_acc=0.4329, lr=2.67061e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 14 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 15/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.5282, train_acc=0.5365
[efficientnet_b0_improved] test_loss=1.7685, test_acc=0.4319, lr=2.32939e-05

[efficientnet_b0_improved] Epoch 16/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.5128, train_acc=0.5462
[efficientnet_b0_improved] test_loss=1.7636, test_acc=0.4371, lr=1.99136e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 16 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 17/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.4950, train_acc=0.5547
[efficientnet_b0_improved] test_loss=1.7723, test_acc=0.4407, lr=1.6628e-05

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 17 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 18/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.4774, train_acc=0.5642
[efficientnet_b0_improved] test_loss=1.7702, test_acc=0.4356, lr=1.34984e-05

[efficientnet_b0_improved] Epoch 19/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.4666, train_acc=0.5669
[efficientnet_b0_improved] test_loss=1.7723, test_acc=0.4386, lr=1.0583e-05

[efficientnet_b0_improved] Epoch 20/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.4582, train_acc=0.5721
[efficientnet_b0_improved] test_loss=1.7670, test_acc=0.4386, lr=7.93617e-06

[efficientnet_b0_improved] Epoch 21/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.4515, train_acc=0.5756
[efficientnet_b0_improved] test_loss=1.7784, test_acc=0.4371, lr=5.60722e-06

[efficientnet_b0_improved] Epoch 22/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.4439, train_acc=0.5782
[efficientnet_b0_improved] test_loss=1.7740, test_acc=0.4389, lr=3.63951e-06

[efficientnet_b0_improved] Epoch 23/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.4429, train_acc=0.5792
[efficientnet_b0_improved] test_loss=1.7734, test_acc=0.4425, lr=2.06972e-06

  0%|          | 0/109 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 23 to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

[efficientnet_b0_improved] Epoch 24/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.4407, train_acc=0.5827
[efficientnet_b0_improved] test_loss=1.7726, test_acc=0.4359, lr=9.27068e-07

[efficientnet_b0_improved] Epoch 25/25

  0%|          | 0/437 [00:00<?, ?it/s]

  0%|          | 0/109 [00:00<?, ?it/s]

[efficientnet_b0_improved] train_loss=1.4372, train_acc=0.5809
[efficientnet_b0_improved] test_loss=1.7676, test_acc=0.4402, lr=2.32851e-07

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()

  0%|          | 0/437 [00:00<?, ?it/s]

==== Final Results ====
efficientnet_b0_improved train=0.6980, test=0.4425, best_epoch=23
Saved metrics to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_metrics.json
Saved model to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best.pt
Saved best test predictions to /content/drive/MyDrive/kaggle_cs3780_sp26/efficientnet_b0_improved/efficientnet_b0_improved_best_test_predictions.csv

       file_name                  label
0  XC1000276.png         Nocturnal bird
1  XC1000366.png  Water-associated bird
2  XC1000546.png  Water-associated bird
3  XC1000940.png         Other songbird
4  XC1000942.png         Other songbird

In [3]:
import copy
import json
import random
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image
from sklearn.metrics import accuracy_score, classification_report
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from tqdm.auto import tqdm


# =========================================================
# 1. Mount Drive and copy dataset to local disk
# =========================================================
from google.colab import drive
drive.mount("/content/drive")

DRIVE_ROOT = Path("/content/drive/MyDrive/kaggle_cs3780_sp26")
DRIVE_DATA_DIR = DRIVE_ROOT / "lowdim_export" / "reduced_64x32"
LOCAL_ROOT = Path("/content/local_data")
LOCAL_DATA_DIR = LOCAL_ROOT / "reduced_64x32"

if LOCAL_DATA_DIR.exists():
    print(f"Local dataset already exists at {LOCAL_DATA_DIR}")
else:
    LOCAL_ROOT.mkdir(parents=True, exist_ok=True)
    print(f"Copying dataset from {DRIVE_DATA_DIR} to {LOCAL_DATA_DIR} ...")
    shutil.copytree(DRIVE_DATA_DIR, LOCAL_DATA_DIR)
    print("Copy complete.")

print("Local train dir:", LOCAL_DATA_DIR / "train")
print("Local test dir:", LOCAL_DATA_DIR / "test")
print("Local solution:", LOCAL_DATA_DIR / "solution.csv")


# =========================================================
# 2. Config
# =========================================================
BASE_DATA_ROOT = LOCAL_ROOT
TRAIN_SUBDIR = Path("reduced_64x32/train")
TEST_SUBDIR = Path("reduced_64x32/test")
SOLUTION_CSV = LOCAL_DATA_DIR / "solution.csv"

OUTPUT_DIR = DRIVE_ROOT / "convnext_tiny_single_run"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_JSON = OUTPUT_DIR / "convnext_tiny_metrics.json"
OUTPUT_MODEL = OUTPUT_DIR / "convnext_tiny_best.pt"
OUTPUT_PRED_CSV = OUTPUT_DIR / "convnext_tiny_best_test_predictions.csv"

IMG_SIZE = 224
BATCH_SIZE = 48
EPOCHS = 20
LR_HEAD = 1e-3
LR_FINETUNE = 3e-5
WEIGHT_DECAY = 1e-4
LABEL_SMOOTHING = 0.1
FREEZE_BACKBONE_EPOCHS = 2
NUM_WORKERS = 2
PATIENCE = 6
SEED = 2026
USE_AMP = True
USE_TTA = True


# =========================================================
# 3. Utilities
# =========================================================
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed(SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
PIN_MEMORY = torch.cuda.is_available()

print("Using device:", DEVICE)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))


def save_json(obj, path: Path):
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)


def model_num_params(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters())


# =========================================================
# 4. Dataset
# =========================================================
class TrainFolderDataset(Dataset):
    def __init__(self, root_dir: Path, transform=None):
        self.root_dir = root_dir
        self.transform = transform

        self.classes = sorted([p.name for p in root_dir.iterdir() if p.is_dir()])
        if not self.classes:
            raise FileNotFoundError(f"No class folders found under {root_dir}")

        self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}
        self.idx_to_class = {i: cls_name for cls_name, i in self.class_to_idx.items()}

        self.samples = []
        for cls_name in self.classes:
            class_dir = root_dir / cls_name
            for img_path in sorted(class_dir.rglob("*.png")):
                self.samples.append((img_path, self.class_to_idx[cls_name]))

        if not self.samples:
            raise FileNotFoundError(f"No PNG files found under {root_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, label


class TestWithSolutionDataset(Dataset):
    def __init__(self, test_dir: Path, solution_csv: Path, class_to_idx: dict[str, int], transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.class_to_idx = class_to_idx

        solution_df = pd.read_csv(solution_csv)
        if "file_name" not in solution_df.columns or "label" not in solution_df.columns:
            raise ValueError("solution.csv must contain columns: file_name, label")

        solution_map = dict(zip(solution_df["file_name"], solution_df["label"]))

        self.samples = []
        image_paths = sorted(test_dir.rglob("*.png"))
        if not image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

        for img_path in image_paths:
            fname = img_path.name
            if fname not in solution_map:
                raise KeyError(f"{fname} not found in solution.csv")
            label_name = solution_map[fname]
            if label_name not in class_to_idx:
                raise KeyError(f"Label {label_name} from solution.csv not found in training classes")
            label_idx = class_to_idx[label_name]
            self.samples.append((img_path, label_idx))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, label, img_path.name


class TestUnlabeledDataset(Dataset):
    def __init__(self, test_dir: Path, transform=None):
        self.test_dir = test_dir
        self.transform = transform
        self.image_paths = sorted(test_dir.rglob("*.png"))
        if not self.image_paths:
            raise FileNotFoundError(f"No PNG files found under {test_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        with Image.open(img_path) as img:
            img = img.convert("RGB")
            if self.transform is not None:
                img = self.transform(img)
        return img, img_path.name


# =========================================================
# 5. Transforms
# =========================================================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomApply(
        [transforms.RandomAffine(degrees=0, translate=(0.05, 0.05))],
        p=0.5,
    ),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])


# =========================================================
# 6. Load data
# =========================================================
train_dir = BASE_DATA_ROOT / TRAIN_SUBDIR
test_dir = BASE_DATA_ROOT / TEST_SUBDIR

train_dataset = TrainFolderDataset(train_dir, transform=train_transform)
test_eval_dataset = TestWithSolutionDataset(
    test_dir=test_dir,
    solution_csv=SOLUTION_CSV,
    class_to_idx=train_dataset.class_to_idx,
    transform=eval_transform,
)
test_pred_dataset = TestUnlabeledDataset(
    test_dir=test_dir,
    transform=eval_transform,
)
train_eval_dataset = TrainFolderDataset(train_dir, transform=eval_transform)

persistent = NUM_WORKERS > 0

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

test_eval_loader = DataLoader(
    test_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

test_pred_loader = DataLoader(
    test_pred_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

train_eval_loader = DataLoader(
    train_eval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    persistent_workers=persistent,
)

num_classes = len(train_dataset.classes)
print("num_classes =", num_classes)
print("num_train =", len(train_dataset))
print("num_test =", len(test_eval_dataset))


# =========================================================
# 7. Model: ConvNeXt-Tiny
# =========================================================
weights = models.ConvNeXt_Tiny_Weights.DEFAULT
model = models.convnext_tiny(weights=weights)
in_features = model.classifier[2].in_features
model.classifier[2] = nn.Linear(in_features, num_classes)
model = model.to(DEVICE)


def freeze_backbone_except_head(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False
    for p in model.classifier[2].parameters():
        p.requires_grad = True


def unfreeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = True


criterion = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)

freeze_backbone_except_head(model)
optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=LR_HEAD,
    weight_decay=WEIGHT_DECAY,
)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)
scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and DEVICE.type == "cuda"))


# =========================================================
# 8. Helpers
# =========================================================
def run_train_epoch(model, loader, criterion, optimizer, scaler, device, use_amp=True):
    model.train()
    total_loss = 0.0
    all_preds = []
    all_labels = []

    use_amp = use_amp and device.type == "cuda"

    for images, labels in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            logits = model(images)
            loss = criterion(logits, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc


@torch.no_grad()
def run_eval_epoch(model, loader, criterion, device, use_amp=True):
    model.eval()
    total_loss = 0.0
    all_preds = []
    all_labels = []
    all_file_names = []

    use_amp = use_amp and device.type == "cuda"

    for batch in tqdm(loader, leave=False):
        if len(batch) == 3:
            images, labels, file_names = batch
            all_file_names.extend(file_names)
        else:
            images, labels = batch

        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        with torch.autocast(device_type="cuda", enabled=use_amp):
            logits = model(images)
            loss = criterion(logits, labels)

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    return avg_loss, acc, np.array(all_labels), np.array(all_preds), all_file_names


@torch.no_grad()
def predict_test(model, loader, idx_to_class, device, use_amp=True, use_tta=False):
    model.eval()
    rows = []
    use_amp = use_amp and device.type == "cuda"

    for images, file_names in tqdm(loader, leave=False):
        images = images.to(device, non_blocking=True)

        if use_tta:
            variants = [
                images,
                torch.roll(images, shifts=1, dims=2),
                torch.roll(images, shifts=-1, dims=2),
                torch.roll(images, shifts=1, dims=3),
                torch.roll(images, shifts=-1, dims=3),
            ]
            logits_sum = 0
            for v in variants:
                with torch.autocast(device_type="cuda", enabled=use_amp):
                    logits_sum = logits_sum + model(v)
            logits = logits_sum / len(variants)
        else:
            with torch.autocast(device_type="cuda", enabled=use_amp):
                logits = model(images)

        preds = logits.argmax(dim=1).cpu().numpy()

        for fname, pred_idx in zip(file_names, preds):
            rows.append({
                "file_name": fname,
                "label": idx_to_class[int(pred_idx)],
            })

    return pd.DataFrame(rows)


# =========================================================
# 9. Training loop
# =========================================================
history = []
best_test_acc = -1.0
best_state = None
best_model_state_dict = None
best_y_true = None
best_y_pred = None
best_epoch = -1
epochs_without_improve = 0

for epoch in range(1, EPOCHS + 1):
    if epoch == FREEZE_BACKBONE_EPOCHS + 1 and FREEZE_BACKBONE_EPOCHS > 0:
        print(f"[convnext_tiny] Unfreezing full backbone at epoch {epoch}")
        unfreeze_all(model)
        optimizer = torch.optim.AdamW(
            model.parameters(),
            lr=LR_FINETUNE,
            weight_decay=WEIGHT_DECAY,
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer,
            T_max=max(EPOCHS - epoch + 1, 1),
        )

    print(f"\n[convnext_tiny] Epoch {epoch}/{EPOCHS}")

    train_loss, train_acc = run_train_epoch(model, train_loader, criterion, optimizer, scaler, DEVICE, USE_AMP)
    test_loss, test_acc, y_true, y_pred, _ = run_eval_epoch(model, test_eval_loader, criterion, DEVICE, USE_AMP)

    print(f"[convnext_tiny] train_loss={train_loss:.4f}, train_acc={train_acc:.4f}")
    print(f"[convnext_tiny] test_loss={test_loss:.4f}, test_acc={test_acc:.4f}, lr={optimizer.param_groups[0]['lr']:.6g}")

    history.append({
        "epoch": epoch,
        "train_loss": float(train_loss),
        "train_accuracy": float(train_acc),
        "test_loss": float(test_loss),
        "test_accuracy": float(test_acc),
        "lr": float(optimizer.param_groups[0]["lr"]),
    })

    if test_acc > best_test_acc:
        best_test_acc = test_acc
        best_epoch = epoch
        best_model_state_dict = copy.deepcopy(model.state_dict())
        best_state = {
            "model_state_dict": best_model_state_dict,
            "classes": train_dataset.classes,
            "epoch": epoch,
            "best_test_accuracy": float(test_acc),
        }
        best_y_true = y_true.copy()
        best_y_pred = y_pred.copy()
        epochs_without_improve = 0

        best_pred_df = predict_test(
            model,
            test_pred_loader,
            train_dataset.idx_to_class,
            DEVICE,
            use_amp=USE_AMP,
            use_tta=USE_TTA,
        )
        best_pred_df.to_csv(OUTPUT_PRED_CSV, index=False)
        print(f"Saved new best prediction CSV at epoch {epoch} to {OUTPUT_PRED_CSV}")
    else:
        epochs_without_improve += 1

    scheduler.step()

    if epochs_without_improve >= PATIENCE:
        print(f"Early stopping after {PATIENCE} epochs without improvement.")
        break


# =========================================================
# 10. Reload best model and save outputs
# =========================================================
model.load_state_dict(best_model_state_dict)

final_train_loss, final_train_acc, _, _, _ = run_eval_epoch(
    model, train_eval_loader, criterion, DEVICE, USE_AMP
)

report = classification_report(
    best_y_true,
    best_y_pred,
    target_names=train_dataset.classes,
    output_dict=True,
    zero_division=0,
)

results = {
    "config": {
        "train_dir": str(train_dir),
        "test_dir": str(test_dir),
        "solution_csv": str(SOLUTION_CSV),
        "img_size": IMG_SIZE,
        "batch_size": BATCH_SIZE,
        "epochs": EPOCHS,
        "lr_head": LR_HEAD,
        "lr_finetune": LR_FINETUNE,
        "weight_decay": WEIGHT_DECAY,
        "label_smoothing": LABEL_SMOOTHING,
        "freeze_backbone_epochs": FREEZE_BACKBONE_EPOCHS,
        "patience": PATIENCE,
        "seed": SEED,
        "device": str(DEVICE),
        "model": "convnext_tiny",
        "use_tta": USE_TTA,
    },
    "num_train": len(train_dataset),
    "num_test": len(test_eval_dataset),
    "num_classes": num_classes,
    "classes": train_dataset.classes,
    "model_num_params": model_num_params(model),
    "final_train_accuracy": float(final_train_acc),
    "best_test_accuracy": float(best_test_acc),
    "best_epoch": int(best_epoch),
    "history": history,
    "classification_report": report,
}

with OUTPUT_JSON.open("w", encoding="utf-8") as f:
    json.dump(results, f, indent=2)

torch.save(best_state, OUTPUT_MODEL)

print("\n==== Final Results ====")
print(f"convnext_tiny train={final_train_acc:.4f}, test={best_test_acc:.4f}, best_epoch={best_epoch}")
print(f"Saved metrics to {OUTPUT_JSON}")
print(f"Saved model to {OUTPUT_MODEL}")
print(f"Saved best test predictions to {OUTPUT_PRED_CSV}")

pd.read_csv(OUTPUT_PRED_CSV).head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Local dataset already exists at /content/local_data/reduced_64x32
Local train dir: /content/local_data/reduced_64x32/train
Local test dir: /content/local_data/reduced_64x32/test
Local solution: /content/local_data/reduced_64x32/solution.csv
Using device: cuda
GPU: Tesla T4
num_classes = 10
num_train = 27908
num_test = 6960

[convnext_tiny] Epoch 1/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=2.0534, train_acc=0.2706
[convnext_tiny] test_loss=2.0104, test_acc=0.2938, lr=0.001

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 1 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 2/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=2.0120, train_acc=0.2952
[convnext_tiny] test_loss=1.9996, test_acc=0.2976, lr=0.000993844

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 2 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv
[convnext_tiny] Unfreezing full backbone at epoch 3

[convnext_tiny] Epoch 3/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.9157, train_acc=0.3474
[convnext_tiny] test_loss=1.8327, test_acc=0.3864, lr=3e-05

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 3 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 4/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.8004, train_acc=0.4030
[convnext_tiny] test_loss=1.7652, test_acc=0.4180, lr=2.97721e-05

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 4 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 5/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.7151, train_acc=0.4422
[convnext_tiny] test_loss=1.7320, test_acc=0.4362, lr=2.90954e-05

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 5 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 6/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.6381, train_acc=0.4809
[convnext_tiny] test_loss=1.7056, test_acc=0.4523, lr=2.79904e-05

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 6 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 7/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.5689, train_acc=0.5183
[convnext_tiny] test_loss=1.6924, test_acc=0.4614, lr=2.64907e-05

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 7 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 8/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.4954, train_acc=0.5540
[convnext_tiny] test_loss=1.6923, test_acc=0.4698, lr=2.46418e-05

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 8 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 9/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.4194, train_acc=0.5932
[convnext_tiny] test_loss=1.7147, test_acc=0.4710, lr=2.25e-05

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 9 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 10/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.3504, train_acc=0.6295
[convnext_tiny] test_loss=1.7182, test_acc=0.4740, lr=2.01303e-05

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 10 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 11/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.2873, train_acc=0.6634
[convnext_tiny] test_loss=1.7219, test_acc=0.4754, lr=1.76047e-05

  0%|          | 0/145 [00:00<?, ?it/s]

Saved new best prediction CSV at epoch 11 to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

[convnext_tiny] Epoch 12/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.2346, train_acc=0.6879
[convnext_tiny] test_loss=1.7495, test_acc=0.4718, lr=1.5e-05

[convnext_tiny] Epoch 13/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.1818, train_acc=0.7164
[convnext_tiny] test_loss=1.7570, test_acc=0.4694, lr=1.23953e-05

[convnext_tiny] Epoch 14/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.1392, train_acc=0.7372
[convnext_tiny] test_loss=1.7685, test_acc=0.4714, lr=9.8697e-06

[convnext_tiny] Epoch 15/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.1015, train_acc=0.7589
[convnext_tiny] test_loss=1.7823, test_acc=0.4681, lr=7.5e-06

[convnext_tiny] Epoch 16/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.0757, train_acc=0.7698
[convnext_tiny] test_loss=1.7886, test_acc=0.4710, lr=5.35819e-06

[convnext_tiny] Epoch 17/20

  0%|          | 0/582 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

[convnext_tiny] train_loss=1.0519, train_acc=0.7832
[convnext_tiny] test_loss=1.8007, test_acc=0.4701, lr=3.50933e-06
Early stopping after 6 epochs without improvement.

  0%|          | 0/582 [00:00<?, ?it/s]

==== Final Results ====
convnext_tiny train=0.7896, test=0.4754, best_epoch=11
Saved metrics to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_metrics.json
Saved model to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best.pt
Saved best test predictions to /content/drive/MyDrive/kaggle_cs3780_sp26/convnext_tiny_single_run/convnext_tiny_best_test_predictions.csv

       file_name                     label
0  XC1000276.png            Nocturnal bird
1  XC1000366.png            Nocturnal bird
2  XC1000546.png              Bird of prey
3  XC1000940.png            Other songbird
4  XC1000942.png  Other non-passerine bird